// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConnectCoreV1PatchNamespacedServiceProxyHandlerFunc turns a function with the right signature into a connect core v1 patch namespaced service proxy handler
type ConnectCoreV1PatchNamespacedServiceProxyHandlerFunc func(ConnectCoreV1PatchNamespacedServiceProxyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectCoreV1PatchNamespacedServiceProxyHandlerFunc) Handle(params ConnectCoreV1PatchNamespacedServiceProxyParams) middleware.Responder {
	return fn(params)
}

// ConnectCoreV1PatchNamespacedServiceProxyHandler interface for that can handle valid connect core v1 patch namespaced service proxy params
type ConnectCoreV1PatchNamespacedServiceProxyHandler interface {
	Handle(ConnectCoreV1PatchNamespacedServiceProxyParams) middleware.Responder
}

// NewConnectCoreV1PatchNamespacedServiceProxy creates a new http.Handler for the connect core v1 patch namespaced service proxy operation
func NewConnectCoreV1PatchNamespacedServiceProxy(ctx *middleware.Context, handler ConnectCoreV1PatchNamespacedServiceProxyHandler) *ConnectCoreV1PatchNamespacedServiceProxy {
	return &ConnectCoreV1PatchNamespacedServiceProxy{Context: ctx, Handler: handler}
}

/*ConnectCoreV1PatchNamespacedServiceProxy swagger:route PATCH /api/v1/namespaces/{namespace}/services/{name}/proxy core_v1 connectCoreV1PatchNamespacedServiceProxy

connect PATCH requests to proxy of Service

*/
type ConnectCoreV1PatchNamespacedServiceProxy struct {
	Context *middleware.Context
	Handler ConnectCoreV1PatchNamespacedServiceProxyHandler
}

func (o *ConnectCoreV1PatchNamespacedServiceProxy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConnectCoreV1PatchNamespacedServiceProxyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
