// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ConnectCoreV1PostNodeProxyOKCode is the HTTP code returned for type ConnectCoreV1PostNodeProxyOK
const ConnectCoreV1PostNodeProxyOKCode int = 200

/*ConnectCoreV1PostNodeProxyOK OK

swagger:response connectCoreV1PostNodeProxyOK
*/
type ConnectCoreV1PostNodeProxyOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewConnectCoreV1PostNodeProxyOK creates ConnectCoreV1PostNodeProxyOK with default headers values
func NewConnectCoreV1PostNodeProxyOK() *ConnectCoreV1PostNodeProxyOK {

	return &ConnectCoreV1PostNodeProxyOK{}
}

// WithPayload adds the payload to the connect core v1 post node proxy o k response
func (o *ConnectCoreV1PostNodeProxyOK) WithPayload(payload string) *ConnectCoreV1PostNodeProxyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the connect core v1 post node proxy o k response
func (o *ConnectCoreV1PostNodeProxyOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConnectCoreV1PostNodeProxyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ConnectCoreV1PostNodeProxyUnauthorizedCode is the HTTP code returned for type ConnectCoreV1PostNodeProxyUnauthorized
const ConnectCoreV1PostNodeProxyUnauthorizedCode int = 401

/*ConnectCoreV1PostNodeProxyUnauthorized Unauthorized

swagger:response connectCoreV1PostNodeProxyUnauthorized
*/
type ConnectCoreV1PostNodeProxyUnauthorized struct {
}

// NewConnectCoreV1PostNodeProxyUnauthorized creates ConnectCoreV1PostNodeProxyUnauthorized with default headers values
func NewConnectCoreV1PostNodeProxyUnauthorized() *ConnectCoreV1PostNodeProxyUnauthorized {

	return &ConnectCoreV1PostNodeProxyUnauthorized{}
}

// WriteResponse to the client
func (o *ConnectCoreV1PostNodeProxyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
