// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// CreateCoreV1NamespacedResourceQuotaOKCode is the HTTP code returned for type CreateCoreV1NamespacedResourceQuotaOK
const CreateCoreV1NamespacedResourceQuotaOKCode int = 200

/*CreateCoreV1NamespacedResourceQuotaOK OK

swagger:response createCoreV1NamespacedResourceQuotaOK
*/
type CreateCoreV1NamespacedResourceQuotaOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPICoreV1ResourceQuota `json:"body,omitempty"`
}

// NewCreateCoreV1NamespacedResourceQuotaOK creates CreateCoreV1NamespacedResourceQuotaOK with default headers values
func NewCreateCoreV1NamespacedResourceQuotaOK() *CreateCoreV1NamespacedResourceQuotaOK {

	return &CreateCoreV1NamespacedResourceQuotaOK{}
}

// WithPayload adds the payload to the create core v1 namespaced resource quota o k response
func (o *CreateCoreV1NamespacedResourceQuotaOK) WithPayload(payload *models.IoK8sAPICoreV1ResourceQuota) *CreateCoreV1NamespacedResourceQuotaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create core v1 namespaced resource quota o k response
func (o *CreateCoreV1NamespacedResourceQuotaOK) SetPayload(payload *models.IoK8sAPICoreV1ResourceQuota) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCoreV1NamespacedResourceQuotaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCoreV1NamespacedResourceQuotaCreatedCode is the HTTP code returned for type CreateCoreV1NamespacedResourceQuotaCreated
const CreateCoreV1NamespacedResourceQuotaCreatedCode int = 201

/*CreateCoreV1NamespacedResourceQuotaCreated Created

swagger:response createCoreV1NamespacedResourceQuotaCreated
*/
type CreateCoreV1NamespacedResourceQuotaCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPICoreV1ResourceQuota `json:"body,omitempty"`
}

// NewCreateCoreV1NamespacedResourceQuotaCreated creates CreateCoreV1NamespacedResourceQuotaCreated with default headers values
func NewCreateCoreV1NamespacedResourceQuotaCreated() *CreateCoreV1NamespacedResourceQuotaCreated {

	return &CreateCoreV1NamespacedResourceQuotaCreated{}
}

// WithPayload adds the payload to the create core v1 namespaced resource quota created response
func (o *CreateCoreV1NamespacedResourceQuotaCreated) WithPayload(payload *models.IoK8sAPICoreV1ResourceQuota) *CreateCoreV1NamespacedResourceQuotaCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create core v1 namespaced resource quota created response
func (o *CreateCoreV1NamespacedResourceQuotaCreated) SetPayload(payload *models.IoK8sAPICoreV1ResourceQuota) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCoreV1NamespacedResourceQuotaCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCoreV1NamespacedResourceQuotaAcceptedCode is the HTTP code returned for type CreateCoreV1NamespacedResourceQuotaAccepted
const CreateCoreV1NamespacedResourceQuotaAcceptedCode int = 202

/*CreateCoreV1NamespacedResourceQuotaAccepted Accepted

swagger:response createCoreV1NamespacedResourceQuotaAccepted
*/
type CreateCoreV1NamespacedResourceQuotaAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPICoreV1ResourceQuota `json:"body,omitempty"`
}

// NewCreateCoreV1NamespacedResourceQuotaAccepted creates CreateCoreV1NamespacedResourceQuotaAccepted with default headers values
func NewCreateCoreV1NamespacedResourceQuotaAccepted() *CreateCoreV1NamespacedResourceQuotaAccepted {

	return &CreateCoreV1NamespacedResourceQuotaAccepted{}
}

// WithPayload adds the payload to the create core v1 namespaced resource quota accepted response
func (o *CreateCoreV1NamespacedResourceQuotaAccepted) WithPayload(payload *models.IoK8sAPICoreV1ResourceQuota) *CreateCoreV1NamespacedResourceQuotaAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create core v1 namespaced resource quota accepted response
func (o *CreateCoreV1NamespacedResourceQuotaAccepted) SetPayload(payload *models.IoK8sAPICoreV1ResourceQuota) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCoreV1NamespacedResourceQuotaAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCoreV1NamespacedResourceQuotaUnauthorizedCode is the HTTP code returned for type CreateCoreV1NamespacedResourceQuotaUnauthorized
const CreateCoreV1NamespacedResourceQuotaUnauthorizedCode int = 401

/*CreateCoreV1NamespacedResourceQuotaUnauthorized Unauthorized

swagger:response createCoreV1NamespacedResourceQuotaUnauthorized
*/
type CreateCoreV1NamespacedResourceQuotaUnauthorized struct {
}

// NewCreateCoreV1NamespacedResourceQuotaUnauthorized creates CreateCoreV1NamespacedResourceQuotaUnauthorized with default headers values
func NewCreateCoreV1NamespacedResourceQuotaUnauthorized() *CreateCoreV1NamespacedResourceQuotaUnauthorized {

	return &CreateCoreV1NamespacedResourceQuotaUnauthorized{}
}

// WriteResponse to the client
func (o *CreateCoreV1NamespacedResourceQuotaUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
