// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchCoreV1NamespacedServiceListHandlerFunc turns a function with the right signature into a watch core v1 namespaced service list handler
type WatchCoreV1NamespacedServiceListHandlerFunc func(WatchCoreV1NamespacedServiceListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchCoreV1NamespacedServiceListHandlerFunc) Handle(params WatchCoreV1NamespacedServiceListParams) middleware.Responder {
	return fn(params)
}

// WatchCoreV1NamespacedServiceListHandler interface for that can handle valid watch core v1 namespaced service list params
type WatchCoreV1NamespacedServiceListHandler interface {
	Handle(WatchCoreV1NamespacedServiceListParams) middleware.Responder
}

// NewWatchCoreV1NamespacedServiceList creates a new http.Handler for the watch core v1 namespaced service list operation
func NewWatchCoreV1NamespacedServiceList(ctx *middleware.Context, handler WatchCoreV1NamespacedServiceListHandler) *WatchCoreV1NamespacedServiceList {
	return &WatchCoreV1NamespacedServiceList{Context: ctx, Handler: handler}
}

/*WatchCoreV1NamespacedServiceList swagger:route GET /api/v1/watch/namespaces/{namespace}/services core_v1 watchCoreV1NamespacedServiceList

watch individual changes to a list of Service. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchCoreV1NamespacedServiceList struct {
	Context *middleware.Context
	Handler WatchCoreV1NamespacedServiceListHandler
}

func (o *WatchCoreV1NamespacedServiceList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchCoreV1NamespacedServiceListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
