// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package coordination_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCoordinationV1NamespacedLeaseHandlerFunc turns a function with the right signature into a delete coordination v1 namespaced lease handler
type DeleteCoordinationV1NamespacedLeaseHandlerFunc func(DeleteCoordinationV1NamespacedLeaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCoordinationV1NamespacedLeaseHandlerFunc) Handle(params DeleteCoordinationV1NamespacedLeaseParams) middleware.Responder {
	return fn(params)
}

// DeleteCoordinationV1NamespacedLeaseHandler interface for that can handle valid delete coordination v1 namespaced lease params
type DeleteCoordinationV1NamespacedLeaseHandler interface {
	Handle(DeleteCoordinationV1NamespacedLeaseParams) middleware.Responder
}

// NewDeleteCoordinationV1NamespacedLease creates a new http.Handler for the delete coordination v1 namespaced lease operation
func NewDeleteCoordinationV1NamespacedLease(ctx *middleware.Context, handler DeleteCoordinationV1NamespacedLeaseHandler) *DeleteCoordinationV1NamespacedLease {
	return &DeleteCoordinationV1NamespacedLease{Context: ctx, Handler: handler}
}

/*DeleteCoordinationV1NamespacedLease swagger:route DELETE /apis/coordination.k8s.io/v1/namespaces/{namespace}/leases/{name} coordination_v1 deleteCoordinationV1NamespacedLease

delete a Lease

*/
type DeleteCoordinationV1NamespacedLease struct {
	Context *middleware.Context
	Handler DeleteCoordinationV1NamespacedLeaseHandler
}

func (o *DeleteCoordinationV1NamespacedLease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCoordinationV1NamespacedLeaseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
