// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package scheduling_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReplaceSchedulingV1PriorityClassOKCode is the HTTP code returned for type ReplaceSchedulingV1PriorityClassOK
const ReplaceSchedulingV1PriorityClassOKCode int = 200

/*ReplaceSchedulingV1PriorityClassOK OK

swagger:response replaceSchedulingV1PriorityClassOK
*/
type ReplaceSchedulingV1PriorityClassOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPISchedulingV1PriorityClass `json:"body,omitempty"`
}

// NewReplaceSchedulingV1PriorityClassOK creates ReplaceSchedulingV1PriorityClassOK with default headers values
func NewReplaceSchedulingV1PriorityClassOK() *ReplaceSchedulingV1PriorityClassOK {

	return &ReplaceSchedulingV1PriorityClassOK{}
}

// WithPayload adds the payload to the replace scheduling v1 priority class o k response
func (o *ReplaceSchedulingV1PriorityClassOK) WithPayload(payload *models.IoK8sAPISchedulingV1PriorityClass) *ReplaceSchedulingV1PriorityClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace scheduling v1 priority class o k response
func (o *ReplaceSchedulingV1PriorityClassOK) SetPayload(payload *models.IoK8sAPISchedulingV1PriorityClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceSchedulingV1PriorityClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceSchedulingV1PriorityClassCreatedCode is the HTTP code returned for type ReplaceSchedulingV1PriorityClassCreated
const ReplaceSchedulingV1PriorityClassCreatedCode int = 201

/*ReplaceSchedulingV1PriorityClassCreated Created

swagger:response replaceSchedulingV1PriorityClassCreated
*/
type ReplaceSchedulingV1PriorityClassCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPISchedulingV1PriorityClass `json:"body,omitempty"`
}

// NewReplaceSchedulingV1PriorityClassCreated creates ReplaceSchedulingV1PriorityClassCreated with default headers values
func NewReplaceSchedulingV1PriorityClassCreated() *ReplaceSchedulingV1PriorityClassCreated {

	return &ReplaceSchedulingV1PriorityClassCreated{}
}

// WithPayload adds the payload to the replace scheduling v1 priority class created response
func (o *ReplaceSchedulingV1PriorityClassCreated) WithPayload(payload *models.IoK8sAPISchedulingV1PriorityClass) *ReplaceSchedulingV1PriorityClassCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace scheduling v1 priority class created response
func (o *ReplaceSchedulingV1PriorityClassCreated) SetPayload(payload *models.IoK8sAPISchedulingV1PriorityClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceSchedulingV1PriorityClassCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceSchedulingV1PriorityClassUnauthorizedCode is the HTTP code returned for type ReplaceSchedulingV1PriorityClassUnauthorized
const ReplaceSchedulingV1PriorityClassUnauthorizedCode int = 401

/*ReplaceSchedulingV1PriorityClassUnauthorized Unauthorized

swagger:response replaceSchedulingV1PriorityClassUnauthorized
*/
type ReplaceSchedulingV1PriorityClassUnauthorized struct {
}

// NewReplaceSchedulingV1PriorityClassUnauthorized creates ReplaceSchedulingV1PriorityClassUnauthorized with default headers values
func NewReplaceSchedulingV1PriorityClassUnauthorized() *ReplaceSchedulingV1PriorityClassUnauthorized {

	return &ReplaceSchedulingV1PriorityClassUnauthorized{}
}

// WriteResponse to the client
func (o *ReplaceSchedulingV1PriorityClassUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
