// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// DeleteAppsV1CollectionNamespacedControllerRevisionReader is a Reader for the DeleteAppsV1CollectionNamespacedControllerRevision structure.
type DeleteAppsV1CollectionNamespacedControllerRevisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppsV1CollectionNamespacedControllerRevisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAppsV1CollectionNamespacedControllerRevisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAppsV1CollectionNamespacedControllerRevisionOK creates a DeleteAppsV1CollectionNamespacedControllerRevisionOK with default headers values
func NewDeleteAppsV1CollectionNamespacedControllerRevisionOK() *DeleteAppsV1CollectionNamespacedControllerRevisionOK {
	return &DeleteAppsV1CollectionNamespacedControllerRevisionOK{}
}

/*DeleteAppsV1CollectionNamespacedControllerRevisionOK handles this case with default header values.

OK
*/
type DeleteAppsV1CollectionNamespacedControllerRevisionOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status
}

func (o *DeleteAppsV1CollectionNamespacedControllerRevisionOK) Error() string {
	return fmt.Sprintf("[DELETE /apis/apps/v1/namespaces/{namespace}/controllerrevisions][%d] deleteAppsV1CollectionNamespacedControllerRevisionOK  %+v", 200, o.Payload)
}

func (o *DeleteAppsV1CollectionNamespacedControllerRevisionOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1Status {
	return o.Payload
}

func (o *DeleteAppsV1CollectionNamespacedControllerRevisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized creates a DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized with default headers values
func NewDeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized() *DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized {
	return &DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized{}
}

/*DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized struct {
}

func (o *DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apis/apps/v1/namespaces/{namespace}/controllerrevisions][%d] deleteAppsV1CollectionNamespacedControllerRevisionUnauthorized ", 401)
}

func (o *DeleteAppsV1CollectionNamespacedControllerRevisionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
