// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchAppsV1StatefulSetListForAllNamespacesReader is a Reader for the WatchAppsV1StatefulSetListForAllNamespaces structure.
type WatchAppsV1StatefulSetListForAllNamespacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchAppsV1StatefulSetListForAllNamespacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchAppsV1StatefulSetListForAllNamespacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchAppsV1StatefulSetListForAllNamespacesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchAppsV1StatefulSetListForAllNamespacesOK creates a WatchAppsV1StatefulSetListForAllNamespacesOK with default headers values
func NewWatchAppsV1StatefulSetListForAllNamespacesOK() *WatchAppsV1StatefulSetListForAllNamespacesOK {
	return &WatchAppsV1StatefulSetListForAllNamespacesOK{}
}

/*WatchAppsV1StatefulSetListForAllNamespacesOK handles this case with default header values.

OK
*/
type WatchAppsV1StatefulSetListForAllNamespacesOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchAppsV1StatefulSetListForAllNamespacesOK) Error() string {
	return fmt.Sprintf("[GET /apis/apps/v1/watch/statefulsets][%d] watchAppsV1StatefulSetListForAllNamespacesOK  %+v", 200, o.Payload)
}

func (o *WatchAppsV1StatefulSetListForAllNamespacesOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchAppsV1StatefulSetListForAllNamespacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchAppsV1StatefulSetListForAllNamespacesUnauthorized creates a WatchAppsV1StatefulSetListForAllNamespacesUnauthorized with default headers values
func NewWatchAppsV1StatefulSetListForAllNamespacesUnauthorized() *WatchAppsV1StatefulSetListForAllNamespacesUnauthorized {
	return &WatchAppsV1StatefulSetListForAllNamespacesUnauthorized{}
}

/*WatchAppsV1StatefulSetListForAllNamespacesUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchAppsV1StatefulSetListForAllNamespacesUnauthorized struct {
}

func (o *WatchAppsV1StatefulSetListForAllNamespacesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/apps/v1/watch/statefulsets][%d] watchAppsV1StatefulSetListForAllNamespacesUnauthorized ", 401)
}

func (o *WatchAppsV1StatefulSetListForAllNamespacesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
