// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package storage_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchStorageV1beta1VolumeAttachmentListReader is a Reader for the WatchStorageV1beta1VolumeAttachmentList structure.
type WatchStorageV1beta1VolumeAttachmentListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchStorageV1beta1VolumeAttachmentListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchStorageV1beta1VolumeAttachmentListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchStorageV1beta1VolumeAttachmentListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchStorageV1beta1VolumeAttachmentListOK creates a WatchStorageV1beta1VolumeAttachmentListOK with default headers values
func NewWatchStorageV1beta1VolumeAttachmentListOK() *WatchStorageV1beta1VolumeAttachmentListOK {
	return &WatchStorageV1beta1VolumeAttachmentListOK{}
}

/*WatchStorageV1beta1VolumeAttachmentListOK handles this case with default header values.

OK
*/
type WatchStorageV1beta1VolumeAttachmentListOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchStorageV1beta1VolumeAttachmentListOK) Error() string {
	return fmt.Sprintf("[GET /apis/storage.k8s.io/v1beta1/watch/volumeattachments][%d] watchStorageV1beta1VolumeAttachmentListOK  %+v", 200, o.Payload)
}

func (o *WatchStorageV1beta1VolumeAttachmentListOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchStorageV1beta1VolumeAttachmentListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchStorageV1beta1VolumeAttachmentListUnauthorized creates a WatchStorageV1beta1VolumeAttachmentListUnauthorized with default headers values
func NewWatchStorageV1beta1VolumeAttachmentListUnauthorized() *WatchStorageV1beta1VolumeAttachmentListUnauthorized {
	return &WatchStorageV1beta1VolumeAttachmentListUnauthorized{}
}

/*WatchStorageV1beta1VolumeAttachmentListUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchStorageV1beta1VolumeAttachmentListUnauthorized struct {
}

func (o *WatchStorageV1beta1VolumeAttachmentListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/storage.k8s.io/v1beta1/watch/volumeattachments][%d] watchStorageV1beta1VolumeAttachmentListUnauthorized ", 401)
}

func (o *WatchStorageV1beta1VolumeAttachmentListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
