// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAppsV1NamespacedReplicaSetHandlerFunc turns a function with the right signature into a delete apps v1 namespaced replica set handler
type DeleteAppsV1NamespacedReplicaSetHandlerFunc func(DeleteAppsV1NamespacedReplicaSetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAppsV1NamespacedReplicaSetHandlerFunc) Handle(params DeleteAppsV1NamespacedReplicaSetParams) middleware.Responder {
	return fn(params)
}

// DeleteAppsV1NamespacedReplicaSetHandler interface for that can handle valid delete apps v1 namespaced replica set params
type DeleteAppsV1NamespacedReplicaSetHandler interface {
	Handle(DeleteAppsV1NamespacedReplicaSetParams) middleware.Responder
}

// NewDeleteAppsV1NamespacedReplicaSet creates a new http.Handler for the delete apps v1 namespaced replica set operation
func NewDeleteAppsV1NamespacedReplicaSet(ctx *middleware.Context, handler DeleteAppsV1NamespacedReplicaSetHandler) *DeleteAppsV1NamespacedReplicaSet {
	return &DeleteAppsV1NamespacedReplicaSet{Context: ctx, Handler: handler}
}

/*DeleteAppsV1NamespacedReplicaSet swagger:route DELETE /apis/apps/v1/namespaces/{namespace}/replicasets/{name} apps_v1 deleteAppsV1NamespacedReplicaSet

delete a ReplicaSet

*/
type DeleteAppsV1NamespacedReplicaSet struct {
	Context *middleware.Context
	Handler DeleteAppsV1NamespacedReplicaSetHandler
}

func (o *DeleteAppsV1NamespacedReplicaSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAppsV1NamespacedReplicaSetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
