// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAppsV1NamespacedControllerRevisionHandlerFunc turns a function with the right signature into a delete apps v1 namespaced controller revision handler
type DeleteAppsV1NamespacedControllerRevisionHandlerFunc func(DeleteAppsV1NamespacedControllerRevisionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAppsV1NamespacedControllerRevisionHandlerFunc) Handle(params DeleteAppsV1NamespacedControllerRevisionParams) middleware.Responder {
	return fn(params)
}

// DeleteAppsV1NamespacedControllerRevisionHandler interface for that can handle valid delete apps v1 namespaced controller revision params
type DeleteAppsV1NamespacedControllerRevisionHandler interface {
	Handle(DeleteAppsV1NamespacedControllerRevisionParams) middleware.Responder
}

// NewDeleteAppsV1NamespacedControllerRevision creates a new http.Handler for the delete apps v1 namespaced controller revision operation
func NewDeleteAppsV1NamespacedControllerRevision(ctx *middleware.Context, handler DeleteAppsV1NamespacedControllerRevisionHandler) *DeleteAppsV1NamespacedControllerRevision {
	return &DeleteAppsV1NamespacedControllerRevision{Context: ctx, Handler: handler}
}

/*DeleteAppsV1NamespacedControllerRevision swagger:route DELETE /apis/apps/v1/namespaces/{namespace}/controllerrevisions/{name} apps_v1 deleteAppsV1NamespacedControllerRevision

delete a ControllerRevision

*/
type DeleteAppsV1NamespacedControllerRevision struct {
	Context *middleware.Context
	Handler DeleteAppsV1NamespacedControllerRevisionHandler
}

func (o *DeleteAppsV1NamespacedControllerRevision) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAppsV1NamespacedControllerRevisionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
