// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceAppsV1NamespacedReplicaSetScaleHandlerFunc turns a function with the right signature into a replace apps v1 namespaced replica set scale handler
type ReplaceAppsV1NamespacedReplicaSetScaleHandlerFunc func(ReplaceAppsV1NamespacedReplicaSetScaleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceAppsV1NamespacedReplicaSetScaleHandlerFunc) Handle(params ReplaceAppsV1NamespacedReplicaSetScaleParams) middleware.Responder {
	return fn(params)
}

// ReplaceAppsV1NamespacedReplicaSetScaleHandler interface for that can handle valid replace apps v1 namespaced replica set scale params
type ReplaceAppsV1NamespacedReplicaSetScaleHandler interface {
	Handle(ReplaceAppsV1NamespacedReplicaSetScaleParams) middleware.Responder
}

// NewReplaceAppsV1NamespacedReplicaSetScale creates a new http.Handler for the replace apps v1 namespaced replica set scale operation
func NewReplaceAppsV1NamespacedReplicaSetScale(ctx *middleware.Context, handler ReplaceAppsV1NamespacedReplicaSetScaleHandler) *ReplaceAppsV1NamespacedReplicaSetScale {
	return &ReplaceAppsV1NamespacedReplicaSetScale{Context: ctx, Handler: handler}
}

/*ReplaceAppsV1NamespacedReplicaSetScale swagger:route PUT /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/scale apps_v1 replaceAppsV1NamespacedReplicaSetScale

replace scale of the specified ReplicaSet

*/
type ReplaceAppsV1NamespacedReplicaSetScale struct {
	Context *middleware.Context
	Handler ReplaceAppsV1NamespacedReplicaSetScaleHandler
}

func (o *ReplaceAppsV1NamespacedReplicaSetScale) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceAppsV1NamespacedReplicaSetScaleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
