// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apps_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// WatchAppsV1DaemonSetListForAllNamespacesHandlerFunc turns a function with the right signature into a watch apps v1 daemon set list for all namespaces handler
type WatchAppsV1DaemonSetListForAllNamespacesHandlerFunc func(WatchAppsV1DaemonSetListForAllNamespacesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn WatchAppsV1DaemonSetListForAllNamespacesHandlerFunc) Handle(params WatchAppsV1DaemonSetListForAllNamespacesParams) middleware.Responder {
	return fn(params)
}

// WatchAppsV1DaemonSetListForAllNamespacesHandler interface for that can handle valid watch apps v1 daemon set list for all namespaces params
type WatchAppsV1DaemonSetListForAllNamespacesHandler interface {
	Handle(WatchAppsV1DaemonSetListForAllNamespacesParams) middleware.Responder
}

// NewWatchAppsV1DaemonSetListForAllNamespaces creates a new http.Handler for the watch apps v1 daemon set list for all namespaces operation
func NewWatchAppsV1DaemonSetListForAllNamespaces(ctx *middleware.Context, handler WatchAppsV1DaemonSetListForAllNamespacesHandler) *WatchAppsV1DaemonSetListForAllNamespaces {
	return &WatchAppsV1DaemonSetListForAllNamespaces{Context: ctx, Handler: handler}
}

/*WatchAppsV1DaemonSetListForAllNamespaces swagger:route GET /apis/apps/v1/watch/daemonsets apps_v1 watchAppsV1DaemonSetListForAllNamespaces

watch individual changes to a list of DaemonSet. deprecated: use the 'watch' parameter with a list operation instead.

*/
type WatchAppsV1DaemonSetListForAllNamespaces struct {
	Context *middleware.Context
	Handler WatchAppsV1DaemonSetListForAllNamespacesHandler
}

func (o *WatchAppsV1DaemonSetListForAllNamespaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWatchAppsV1DaemonSetListForAllNamespacesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
