// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apiextensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetApiextensionsAPIGroupParams creates a new GetApiextensionsAPIGroupParams object
// with the default values initialized.
func NewGetApiextensionsAPIGroupParams() *GetApiextensionsAPIGroupParams {

	return &GetApiextensionsAPIGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApiextensionsAPIGroupParamsWithTimeout creates a new GetApiextensionsAPIGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApiextensionsAPIGroupParamsWithTimeout(timeout time.Duration) *GetApiextensionsAPIGroupParams {

	return &GetApiextensionsAPIGroupParams{

		timeout: timeout,
	}
}

// NewGetApiextensionsAPIGroupParamsWithContext creates a new GetApiextensionsAPIGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApiextensionsAPIGroupParamsWithContext(ctx context.Context) *GetApiextensionsAPIGroupParams {

	return &GetApiextensionsAPIGroupParams{

		Context: ctx,
	}
}

// NewGetApiextensionsAPIGroupParamsWithHTTPClient creates a new GetApiextensionsAPIGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApiextensionsAPIGroupParamsWithHTTPClient(client *http.Client) *GetApiextensionsAPIGroupParams {

	return &GetApiextensionsAPIGroupParams{
		HTTPClient: client,
	}
}

/*GetApiextensionsAPIGroupParams contains all the parameters to send to the API endpoint
for the get apiextensions API group operation typically these are written to a http.Request
*/
type GetApiextensionsAPIGroupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) WithTimeout(timeout time.Duration) *GetApiextensionsAPIGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) WithContext(ctx context.Context) *GetApiextensionsAPIGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) WithHTTPClient(client *http.Client) *GetApiextensionsAPIGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apiextensions API group params
func (o *GetApiextensionsAPIGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetApiextensionsAPIGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
