// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package rbac_authorization_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// DeleteRbacAuthorizationV1beta1NamespacedRoleReader is a Reader for the DeleteRbacAuthorizationV1beta1NamespacedRole structure.
type DeleteRbacAuthorizationV1beta1NamespacedRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRbacAuthorizationV1beta1NamespacedRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewDeleteRbacAuthorizationV1beta1NamespacedRoleAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRbacAuthorizationV1beta1NamespacedRoleOK creates a DeleteRbacAuthorizationV1beta1NamespacedRoleOK with default headers values
func NewDeleteRbacAuthorizationV1beta1NamespacedRoleOK() *DeleteRbacAuthorizationV1beta1NamespacedRoleOK {
	return &DeleteRbacAuthorizationV1beta1NamespacedRoleOK{}
}

/*DeleteRbacAuthorizationV1beta1NamespacedRoleOK handles this case with default header values.

OK
*/
type DeleteRbacAuthorizationV1beta1NamespacedRoleOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleOK) Error() string {
	return fmt.Sprintf("[DELETE /apis/rbac.authorization.k8s.io/v1beta1/namespaces/{namespace}/roles/{name}][%d] deleteRbacAuthorizationV1beta1NamespacedRoleOK  %+v", 200, o.Payload)
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1Status {
	return o.Payload
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRbacAuthorizationV1beta1NamespacedRoleAccepted creates a DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted with default headers values
func NewDeleteRbacAuthorizationV1beta1NamespacedRoleAccepted() *DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted {
	return &DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted{}
}

/*DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted handles this case with default header values.

Accepted
*/
type DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted) Error() string {
	return fmt.Sprintf("[DELETE /apis/rbac.authorization.k8s.io/v1beta1/namespaces/{namespace}/roles/{name}][%d] deleteRbacAuthorizationV1beta1NamespacedRoleAccepted  %+v", 202, o.Payload)
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1Status {
	return o.Payload
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized creates a DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized with default headers values
func NewDeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized() *DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized {
	return &DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized{}
}

/*DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized struct {
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /apis/rbac.authorization.k8s.io/v1beta1/namespaces/{namespace}/roles/{name}][%d] deleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized ", 401)
}

func (o *DeleteRbacAuthorizationV1beta1NamespacedRoleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
