// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package cilium

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostManagementCiliumIoV2CiliumEndpointsOKCode is the HTTP code returned for type PostManagementCiliumIoV2CiliumEndpointsOK
const PostManagementCiliumIoV2CiliumEndpointsOKCode int = 200

/*PostManagementCiliumIoV2CiliumEndpointsOK OK

swagger:response postManagementCiliumIoV2CiliumEndpointsOK
*/
type PostManagementCiliumIoV2CiliumEndpointsOK struct {
}

// NewPostManagementCiliumIoV2CiliumEndpointsOK creates PostManagementCiliumIoV2CiliumEndpointsOK with default headers values
func NewPostManagementCiliumIoV2CiliumEndpointsOK() *PostManagementCiliumIoV2CiliumEndpointsOK {

	return &PostManagementCiliumIoV2CiliumEndpointsOK{}
}

// WriteResponse to the client
func (o *PostManagementCiliumIoV2CiliumEndpointsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostManagementCiliumIoV2CiliumEndpointsAcceptedCode is the HTTP code returned for type PostManagementCiliumIoV2CiliumEndpointsAccepted
const PostManagementCiliumIoV2CiliumEndpointsAcceptedCode int = 202

/*PostManagementCiliumIoV2CiliumEndpointsAccepted Accepted

swagger:response postManagementCiliumIoV2CiliumEndpointsAccepted
*/
type PostManagementCiliumIoV2CiliumEndpointsAccepted struct {
}

// NewPostManagementCiliumIoV2CiliumEndpointsAccepted creates PostManagementCiliumIoV2CiliumEndpointsAccepted with default headers values
func NewPostManagementCiliumIoV2CiliumEndpointsAccepted() *PostManagementCiliumIoV2CiliumEndpointsAccepted {

	return &PostManagementCiliumIoV2CiliumEndpointsAccepted{}
}

// WriteResponse to the client
func (o *PostManagementCiliumIoV2CiliumEndpointsAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}
