// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package policy_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOKCode is the HTTP code returned for type ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK
const ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOKCode int = 200

/*ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK OK

swagger:response listPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK
*/
type ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudgetList `json:"body,omitempty"`
}

// NewListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK creates ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK with default headers values
func NewListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK() *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK {

	return &ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK{}
}

// WithPayload adds the payload to the list policy v1beta1 pod disruption budget for all namespaces o k response
func (o *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK) WithPayload(payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudgetList) *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list policy v1beta1 pod disruption budget for all namespaces o k response
func (o *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK) SetPayload(payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudgetList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorizedCode is the HTTP code returned for type ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized
const ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorizedCode int = 401

/*ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized Unauthorized

swagger:response listPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized
*/
type ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized struct {
}

// NewListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized creates ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized with default headers values
func NewListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized() *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized {

	return &ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized{}
}

// WriteResponse to the client
func (o *ListPolicyV1beta1PodDisruptionBudgetForAllNamespacesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
