// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package policy_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReadPolicyV1beta1NamespacedPodDisruptionBudgetOKCode is the HTTP code returned for type ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK
const ReadPolicyV1beta1NamespacedPodDisruptionBudgetOKCode int = 200

/*ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK OK

swagger:response readPolicyV1beta1NamespacedPodDisruptionBudgetOK
*/
type ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudget `json:"body,omitempty"`
}

// NewReadPolicyV1beta1NamespacedPodDisruptionBudgetOK creates ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK with default headers values
func NewReadPolicyV1beta1NamespacedPodDisruptionBudgetOK() *ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK {

	return &ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK{}
}

// WithPayload adds the payload to the read policy v1beta1 namespaced pod disruption budget o k response
func (o *ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK) WithPayload(payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudget) *ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read policy v1beta1 namespaced pod disruption budget o k response
func (o *ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK) SetPayload(payload *models.IoK8sAPIPolicyV1beta1PodDisruptionBudget) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadPolicyV1beta1NamespacedPodDisruptionBudgetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorizedCode is the HTTP code returned for type ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized
const ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorizedCode int = 401

/*ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized Unauthorized

swagger:response readPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized
*/
type ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized struct {
}

// NewReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized creates ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized with default headers values
func NewReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized() *ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized {

	return &ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized{}
}

// WriteResponse to the client
func (o *ReadPolicyV1beta1NamespacedPodDisruptionBudgetUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
