// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package settings_v1alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSettingsV1alpha1NamespacedPodPresetHandlerFunc turns a function with the right signature into a delete settings v1alpha1 namespaced pod preset handler
type DeleteSettingsV1alpha1NamespacedPodPresetHandlerFunc func(DeleteSettingsV1alpha1NamespacedPodPresetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSettingsV1alpha1NamespacedPodPresetHandlerFunc) Handle(params DeleteSettingsV1alpha1NamespacedPodPresetParams) middleware.Responder {
	return fn(params)
}

// DeleteSettingsV1alpha1NamespacedPodPresetHandler interface for that can handle valid delete settings v1alpha1 namespaced pod preset params
type DeleteSettingsV1alpha1NamespacedPodPresetHandler interface {
	Handle(DeleteSettingsV1alpha1NamespacedPodPresetParams) middleware.Responder
}

// NewDeleteSettingsV1alpha1NamespacedPodPreset creates a new http.Handler for the delete settings v1alpha1 namespaced pod preset operation
func NewDeleteSettingsV1alpha1NamespacedPodPreset(ctx *middleware.Context, handler DeleteSettingsV1alpha1NamespacedPodPresetHandler) *DeleteSettingsV1alpha1NamespacedPodPreset {
	return &DeleteSettingsV1alpha1NamespacedPodPreset{Context: ctx, Handler: handler}
}

/*DeleteSettingsV1alpha1NamespacedPodPreset swagger:route DELETE /apis/settings.k8s.io/v1alpha1/namespaces/{namespace}/podpresets/{name} settings_v1alpha1 deleteSettingsV1alpha1NamespacedPodPreset

delete a PodPreset

*/
type DeleteSettingsV1alpha1NamespacedPodPreset struct {
	Context *middleware.Context
	Handler DeleteSettingsV1alpha1NamespacedPodPresetHandler
}

func (o *DeleteSettingsV1alpha1NamespacedPodPreset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSettingsV1alpha1NamespacedPodPresetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
