// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package rbac_authorization_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// DeleteRbacAuthorizationV1beta1ClusterRoleOKCode is the HTTP code returned for type DeleteRbacAuthorizationV1beta1ClusterRoleOK
const DeleteRbacAuthorizationV1beta1ClusterRoleOKCode int = 200

/*DeleteRbacAuthorizationV1beta1ClusterRoleOK OK

swagger:response deleteRbacAuthorizationV1beta1ClusterRoleOK
*/
type DeleteRbacAuthorizationV1beta1ClusterRoleOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status `json:"body,omitempty"`
}

// NewDeleteRbacAuthorizationV1beta1ClusterRoleOK creates DeleteRbacAuthorizationV1beta1ClusterRoleOK with default headers values
func NewDeleteRbacAuthorizationV1beta1ClusterRoleOK() *DeleteRbacAuthorizationV1beta1ClusterRoleOK {

	return &DeleteRbacAuthorizationV1beta1ClusterRoleOK{}
}

// WithPayload adds the payload to the delete rbac authorization v1beta1 cluster role o k response
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) *DeleteRbacAuthorizationV1beta1ClusterRoleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete rbac authorization v1beta1 cluster role o k response
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRbacAuthorizationV1beta1ClusterRoleAcceptedCode is the HTTP code returned for type DeleteRbacAuthorizationV1beta1ClusterRoleAccepted
const DeleteRbacAuthorizationV1beta1ClusterRoleAcceptedCode int = 202

/*DeleteRbacAuthorizationV1beta1ClusterRoleAccepted Accepted

swagger:response deleteRbacAuthorizationV1beta1ClusterRoleAccepted
*/
type DeleteRbacAuthorizationV1beta1ClusterRoleAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status `json:"body,omitempty"`
}

// NewDeleteRbacAuthorizationV1beta1ClusterRoleAccepted creates DeleteRbacAuthorizationV1beta1ClusterRoleAccepted with default headers values
func NewDeleteRbacAuthorizationV1beta1ClusterRoleAccepted() *DeleteRbacAuthorizationV1beta1ClusterRoleAccepted {

	return &DeleteRbacAuthorizationV1beta1ClusterRoleAccepted{}
}

// WithPayload adds the payload to the delete rbac authorization v1beta1 cluster role accepted response
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleAccepted) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) *DeleteRbacAuthorizationV1beta1ClusterRoleAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete rbac authorization v1beta1 cluster role accepted response
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleAccepted) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorizedCode is the HTTP code returned for type DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized
const DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorizedCode int = 401

/*DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized Unauthorized

swagger:response deleteRbacAuthorizationV1beta1ClusterRoleUnauthorized
*/
type DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized struct {
}

// NewDeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized creates DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized with default headers values
func NewDeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized() *DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized {

	return &DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteRbacAuthorizationV1beta1ClusterRoleUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
