// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package discovery_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReplaceDiscoveryV1beta1NamespacedEndpointSliceReader is a Reader for the ReplaceDiscoveryV1beta1NamespacedEndpointSlice structure.
type ReplaceDiscoveryV1beta1NamespacedEndpointSliceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceDiscoveryV1beta1NamespacedEndpointSliceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReplaceDiscoveryV1beta1NamespacedEndpointSliceOK creates a ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK with default headers values
func NewReplaceDiscoveryV1beta1NamespacedEndpointSliceOK() *ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK {
	return &ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK{}
}

/*ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK handles this case with default header values.

OK
*/
type ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK struct {
	Payload *models.IoK8sAPIDiscoveryV1beta1EndpointSlice
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK) Error() string {
	return fmt.Sprintf("[PUT /apis/discovery.k8s.io/v1beta1/namespaces/{namespace}/endpointslices/{name}][%d] replaceDiscoveryV1beta1NamespacedEndpointSliceOK  %+v", 200, o.Payload)
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK) GetPayload() *models.IoK8sAPIDiscoveryV1beta1EndpointSlice {
	return o.Payload
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPIDiscoveryV1beta1EndpointSlice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated creates a ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated with default headers values
func NewReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated() *ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated {
	return &ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated{}
}

/*ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated handles this case with default header values.

Created
*/
type ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated struct {
	Payload *models.IoK8sAPIDiscoveryV1beta1EndpointSlice
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated) Error() string {
	return fmt.Sprintf("[PUT /apis/discovery.k8s.io/v1beta1/namespaces/{namespace}/endpointslices/{name}][%d] replaceDiscoveryV1beta1NamespacedEndpointSliceCreated  %+v", 201, o.Payload)
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated) GetPayload() *models.IoK8sAPIDiscoveryV1beta1EndpointSlice {
	return o.Payload
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPIDiscoveryV1beta1EndpointSlice)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized creates a ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized with default headers values
func NewReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized() *ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized {
	return &ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized{}
}

/*ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized handles this case with default header values.

Unauthorized
*/
type ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized struct {
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /apis/discovery.k8s.io/v1beta1/namespaces/{namespace}/endpointslices/{name}][%d] replaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized ", 401)
}

func (o *ReplaceDiscoveryV1beta1NamespacedEndpointSliceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
