// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package cilium

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListApisCiliumIoV2CiliumEndpointOKCode is the HTTP code returned for type ListApisCiliumIoV2CiliumEndpointOK
const ListApisCiliumIoV2CiliumEndpointOKCode int = 200

/*ListApisCiliumIoV2CiliumEndpointOK OK

swagger:response listApisCiliumIoV2CiliumEndpointOK
*/
type ListApisCiliumIoV2CiliumEndpointOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListApisCiliumIoV2CiliumEndpointOK creates ListApisCiliumIoV2CiliumEndpointOK with default headers values
func NewListApisCiliumIoV2CiliumEndpointOK() *ListApisCiliumIoV2CiliumEndpointOK {

	return &ListApisCiliumIoV2CiliumEndpointOK{}
}

// WithPayload adds the payload to the list apis cilium io v2 cilium endpoint o k response
func (o *ListApisCiliumIoV2CiliumEndpointOK) WithPayload(payload interface{}) *ListApisCiliumIoV2CiliumEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list apis cilium io v2 cilium endpoint o k response
func (o *ListApisCiliumIoV2CiliumEndpointOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListApisCiliumIoV2CiliumEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListApisCiliumIoV2CiliumEndpointUnauthorizedCode is the HTTP code returned for type ListApisCiliumIoV2CiliumEndpointUnauthorized
const ListApisCiliumIoV2CiliumEndpointUnauthorizedCode int = 401

/*ListApisCiliumIoV2CiliumEndpointUnauthorized Unauthorized

swagger:response listApisCiliumIoV2CiliumEndpointUnauthorized
*/
type ListApisCiliumIoV2CiliumEndpointUnauthorized struct {
}

// NewListApisCiliumIoV2CiliumEndpointUnauthorized creates ListApisCiliumIoV2CiliumEndpointUnauthorized with default headers values
func NewListApisCiliumIoV2CiliumEndpointUnauthorized() *ListApisCiliumIoV2CiliumEndpointUnauthorized {

	return &ListApisCiliumIoV2CiliumEndpointUnauthorized{}
}

// WriteResponse to the client
func (o *ListApisCiliumIoV2CiliumEndpointUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
