// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package apiregistration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetApiregistrationAPIGroupParams creates a new GetApiregistrationAPIGroupParams object
// with the default values initialized.
func NewGetApiregistrationAPIGroupParams() *GetApiregistrationAPIGroupParams {

	return &GetApiregistrationAPIGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApiregistrationAPIGroupParamsWithTimeout creates a new GetApiregistrationAPIGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApiregistrationAPIGroupParamsWithTimeout(timeout time.Duration) *GetApiregistrationAPIGroupParams {

	return &GetApiregistrationAPIGroupParams{

		timeout: timeout,
	}
}

// NewGetApiregistrationAPIGroupParamsWithContext creates a new GetApiregistrationAPIGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApiregistrationAPIGroupParamsWithContext(ctx context.Context) *GetApiregistrationAPIGroupParams {

	return &GetApiregistrationAPIGroupParams{

		Context: ctx,
	}
}

// NewGetApiregistrationAPIGroupParamsWithHTTPClient creates a new GetApiregistrationAPIGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApiregistrationAPIGroupParamsWithHTTPClient(client *http.Client) *GetApiregistrationAPIGroupParams {

	return &GetApiregistrationAPIGroupParams{
		HTTPClient: client,
	}
}

/*GetApiregistrationAPIGroupParams contains all the parameters to send to the API endpoint
for the get apiregistration API group operation typically these are written to a http.Request
*/
type GetApiregistrationAPIGroupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) WithTimeout(timeout time.Duration) *GetApiregistrationAPIGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) WithContext(ctx context.Context) *GetApiregistrationAPIGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) WithHTTPClient(client *http.Client) *GetApiregistrationAPIGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apiregistration API group params
func (o *GetApiregistrationAPIGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetApiregistrationAPIGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
