// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package discovery_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteDiscoveryV1beta1NamespacedEndpointSliceHandlerFunc turns a function with the right signature into a delete discovery v1beta1 namespaced endpoint slice handler
type DeleteDiscoveryV1beta1NamespacedEndpointSliceHandlerFunc func(DeleteDiscoveryV1beta1NamespacedEndpointSliceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDiscoveryV1beta1NamespacedEndpointSliceHandlerFunc) Handle(params DeleteDiscoveryV1beta1NamespacedEndpointSliceParams) middleware.Responder {
	return fn(params)
}

// DeleteDiscoveryV1beta1NamespacedEndpointSliceHandler interface for that can handle valid delete discovery v1beta1 namespaced endpoint slice params
type DeleteDiscoveryV1beta1NamespacedEndpointSliceHandler interface {
	Handle(DeleteDiscoveryV1beta1NamespacedEndpointSliceParams) middleware.Responder
}

// NewDeleteDiscoveryV1beta1NamespacedEndpointSlice creates a new http.Handler for the delete discovery v1beta1 namespaced endpoint slice operation
func NewDeleteDiscoveryV1beta1NamespacedEndpointSlice(ctx *middleware.Context, handler DeleteDiscoveryV1beta1NamespacedEndpointSliceHandler) *DeleteDiscoveryV1beta1NamespacedEndpointSlice {
	return &DeleteDiscoveryV1beta1NamespacedEndpointSlice{Context: ctx, Handler: handler}
}

/*DeleteDiscoveryV1beta1NamespacedEndpointSlice swagger:route DELETE /apis/discovery.k8s.io/v1beta1/namespaces/{namespace}/endpointslices/{name} discovery_v1beta1 deleteDiscoveryV1beta1NamespacedEndpointSlice

delete an EndpointSlice

*/
type DeleteDiscoveryV1beta1NamespacedEndpointSlice struct {
	Context *middleware.Context
	Handler DeleteDiscoveryV1beta1NamespacedEndpointSliceHandler
}

func (o *DeleteDiscoveryV1beta1NamespacedEndpointSlice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDiscoveryV1beta1NamespacedEndpointSliceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
