// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package batch_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// PatchBatchV1NamespacedJobOKCode is the HTTP code returned for type PatchBatchV1NamespacedJobOK
const PatchBatchV1NamespacedJobOKCode int = 200

/*PatchBatchV1NamespacedJobOK OK

swagger:response patchBatchV1NamespacedJobOK
*/
type PatchBatchV1NamespacedJobOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIBatchV1Job `json:"body,omitempty"`
}

// NewPatchBatchV1NamespacedJobOK creates PatchBatchV1NamespacedJobOK with default headers values
func NewPatchBatchV1NamespacedJobOK() *PatchBatchV1NamespacedJobOK {

	return &PatchBatchV1NamespacedJobOK{}
}

// WithPayload adds the payload to the patch batch v1 namespaced job o k response
func (o *PatchBatchV1NamespacedJobOK) WithPayload(payload *models.IoK8sAPIBatchV1Job) *PatchBatchV1NamespacedJobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch batch v1 namespaced job o k response
func (o *PatchBatchV1NamespacedJobOK) SetPayload(payload *models.IoK8sAPIBatchV1Job) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBatchV1NamespacedJobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchBatchV1NamespacedJobUnauthorizedCode is the HTTP code returned for type PatchBatchV1NamespacedJobUnauthorized
const PatchBatchV1NamespacedJobUnauthorizedCode int = 401

/*PatchBatchV1NamespacedJobUnauthorized Unauthorized

swagger:response patchBatchV1NamespacedJobUnauthorized
*/
type PatchBatchV1NamespacedJobUnauthorized struct {
}

// NewPatchBatchV1NamespacedJobUnauthorized creates PatchBatchV1NamespacedJobUnauthorized with default headers values
func NewPatchBatchV1NamespacedJobUnauthorized() *PatchBatchV1NamespacedJobUnauthorized {

	return &PatchBatchV1NamespacedJobUnauthorized{}
}

// WriteResponse to the client
func (o *PatchBatchV1NamespacedJobUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
