// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package networking_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ListNetworkingV1NamespacedNetworkPolicyReader is a Reader for the ListNetworkingV1NamespacedNetworkPolicy structure.
type ListNetworkingV1NamespacedNetworkPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNetworkingV1NamespacedNetworkPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNetworkingV1NamespacedNetworkPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListNetworkingV1NamespacedNetworkPolicyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListNetworkingV1NamespacedNetworkPolicyOK creates a ListNetworkingV1NamespacedNetworkPolicyOK with default headers values
func NewListNetworkingV1NamespacedNetworkPolicyOK() *ListNetworkingV1NamespacedNetworkPolicyOK {
	return &ListNetworkingV1NamespacedNetworkPolicyOK{}
}

/*ListNetworkingV1NamespacedNetworkPolicyOK handles this case with default header values.

OK
*/
type ListNetworkingV1NamespacedNetworkPolicyOK struct {
	Payload *models.IoK8sAPINetworkingV1NetworkPolicyList
}

func (o *ListNetworkingV1NamespacedNetworkPolicyOK) Error() string {
	return fmt.Sprintf("[GET /apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies][%d] listNetworkingV1NamespacedNetworkPolicyOK  %+v", 200, o.Payload)
}

func (o *ListNetworkingV1NamespacedNetworkPolicyOK) GetPayload() *models.IoK8sAPINetworkingV1NetworkPolicyList {
	return o.Payload
}

func (o *ListNetworkingV1NamespacedNetworkPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPINetworkingV1NetworkPolicyList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNetworkingV1NamespacedNetworkPolicyUnauthorized creates a ListNetworkingV1NamespacedNetworkPolicyUnauthorized with default headers values
func NewListNetworkingV1NamespacedNetworkPolicyUnauthorized() *ListNetworkingV1NamespacedNetworkPolicyUnauthorized {
	return &ListNetworkingV1NamespacedNetworkPolicyUnauthorized{}
}

/*ListNetworkingV1NamespacedNetworkPolicyUnauthorized handles this case with default header values.

Unauthorized
*/
type ListNetworkingV1NamespacedNetworkPolicyUnauthorized struct {
}

func (o *ListNetworkingV1NamespacedNetworkPolicyUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/networking.k8s.io/v1/namespaces/{namespace}/networkpolicies][%d] listNetworkingV1NamespacedNetworkPolicyUnauthorized ", 401)
}

func (o *ListNetworkingV1NamespacedNetworkPolicyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
