// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package networking_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchNetworkingV1IngressClassReader is a Reader for the WatchNetworkingV1IngressClass structure.
type WatchNetworkingV1IngressClassReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchNetworkingV1IngressClassReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchNetworkingV1IngressClassOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchNetworkingV1IngressClassUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchNetworkingV1IngressClassOK creates a WatchNetworkingV1IngressClassOK with default headers values
func NewWatchNetworkingV1IngressClassOK() *WatchNetworkingV1IngressClassOK {
	return &WatchNetworkingV1IngressClassOK{}
}

/*WatchNetworkingV1IngressClassOK handles this case with default header values.

OK
*/
type WatchNetworkingV1IngressClassOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchNetworkingV1IngressClassOK) Error() string {
	return fmt.Sprintf("[GET /apis/networking.k8s.io/v1/watch/ingressclasses/{name}][%d] watchNetworkingV1IngressClassOK  %+v", 200, o.Payload)
}

func (o *WatchNetworkingV1IngressClassOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchNetworkingV1IngressClassOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchNetworkingV1IngressClassUnauthorized creates a WatchNetworkingV1IngressClassUnauthorized with default headers values
func NewWatchNetworkingV1IngressClassUnauthorized() *WatchNetworkingV1IngressClassUnauthorized {
	return &WatchNetworkingV1IngressClassUnauthorized{}
}

/*WatchNetworkingV1IngressClassUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchNetworkingV1IngressClassUnauthorized struct {
}

func (o *WatchNetworkingV1IngressClassUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/networking.k8s.io/v1/watch/ingressclasses/{name}][%d] watchNetworkingV1IngressClassUnauthorized ", 401)
}

func (o *WatchNetworkingV1IngressClassUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
