// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package batch_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// NewCreateBatchV1NamespacedJobParams creates a new CreateBatchV1NamespacedJobParams object
// with the default values initialized.
func NewCreateBatchV1NamespacedJobParams() *CreateBatchV1NamespacedJobParams {
	var ()
	return &CreateBatchV1NamespacedJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBatchV1NamespacedJobParamsWithTimeout creates a new CreateBatchV1NamespacedJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateBatchV1NamespacedJobParamsWithTimeout(timeout time.Duration) *CreateBatchV1NamespacedJobParams {
	var ()
	return &CreateBatchV1NamespacedJobParams{

		timeout: timeout,
	}
}

// NewCreateBatchV1NamespacedJobParamsWithContext creates a new CreateBatchV1NamespacedJobParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateBatchV1NamespacedJobParamsWithContext(ctx context.Context) *CreateBatchV1NamespacedJobParams {
	var ()
	return &CreateBatchV1NamespacedJobParams{

		Context: ctx,
	}
}

// NewCreateBatchV1NamespacedJobParamsWithHTTPClient creates a new CreateBatchV1NamespacedJobParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateBatchV1NamespacedJobParamsWithHTTPClient(client *http.Client) *CreateBatchV1NamespacedJobParams {
	var ()
	return &CreateBatchV1NamespacedJobParams{
		HTTPClient: client,
	}
}

/*CreateBatchV1NamespacedJobParams contains all the parameters to send to the API endpoint
for the create batch v1 namespaced job operation typically these are written to a http.Request
*/
type CreateBatchV1NamespacedJobParams struct {

	/*Body*/
	Body *models.IoK8sAPIBatchV1Job
	/*DryRun
	  When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed

	*/
	DryRun *string
	/*FieldManager
	  fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.

	*/
	FieldManager *string
	/*Namespace
	  object name and auth scope, such as for teams and projects

	*/
	Namespace string
	/*Pretty
	  If 'true', then the output is pretty printed.

	*/
	Pretty *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithTimeout(timeout time.Duration) *CreateBatchV1NamespacedJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithContext(ctx context.Context) *CreateBatchV1NamespacedJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithHTTPClient(client *http.Client) *CreateBatchV1NamespacedJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithBody(body *models.IoK8sAPIBatchV1Job) *CreateBatchV1NamespacedJobParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetBody(body *models.IoK8sAPIBatchV1Job) {
	o.Body = body
}

// WithDryRun adds the dryRun to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithDryRun(dryRun *string) *CreateBatchV1NamespacedJobParams {
	o.SetDryRun(dryRun)
	return o
}

// SetDryRun adds the dryRun to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetDryRun(dryRun *string) {
	o.DryRun = dryRun
}

// WithFieldManager adds the fieldManager to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithFieldManager(fieldManager *string) *CreateBatchV1NamespacedJobParams {
	o.SetFieldManager(fieldManager)
	return o
}

// SetFieldManager adds the fieldManager to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetFieldManager(fieldManager *string) {
	o.FieldManager = fieldManager
}

// WithNamespace adds the namespace to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithNamespace(namespace string) *CreateBatchV1NamespacedJobParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPretty adds the pretty to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) WithPretty(pretty *string) *CreateBatchV1NamespacedJobParams {
	o.SetPretty(pretty)
	return o
}

// SetPretty adds the pretty to the create batch v1 namespaced job params
func (o *CreateBatchV1NamespacedJobParams) SetPretty(pretty *string) {
	o.Pretty = pretty
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBatchV1NamespacedJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.DryRun != nil {

		// query param dryRun
		var qrDryRun string
		if o.DryRun != nil {
			qrDryRun = *o.DryRun
		}
		qDryRun := qrDryRun
		if qDryRun != "" {
			if err := r.SetQueryParam("dryRun", qDryRun); err != nil {
				return err
			}
		}

	}

	if o.FieldManager != nil {

		// query param fieldManager
		var qrFieldManager string
		if o.FieldManager != nil {
			qrFieldManager = *o.FieldManager
		}
		qFieldManager := qrFieldManager
		if qFieldManager != "" {
			if err := r.SetQueryParam("fieldManager", qFieldManager); err != nil {
				return err
			}
		}

	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Pretty != nil {

		// query param pretty
		var qrPretty string
		if o.Pretty != nil {
			qrPretty = *o.Pretty
		}
		qPretty := qrPretty
		if qPretty != "" {
			if err := r.SetQueryParam("pretty", qPretty); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
