// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package batch_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReadBatchV1NamespacedJobReader is a Reader for the ReadBatchV1NamespacedJob structure.
type ReadBatchV1NamespacedJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadBatchV1NamespacedJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadBatchV1NamespacedJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewReadBatchV1NamespacedJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReadBatchV1NamespacedJobOK creates a ReadBatchV1NamespacedJobOK with default headers values
func NewReadBatchV1NamespacedJobOK() *ReadBatchV1NamespacedJobOK {
	return &ReadBatchV1NamespacedJobOK{}
}

/*ReadBatchV1NamespacedJobOK handles this case with default header values.

OK
*/
type ReadBatchV1NamespacedJobOK struct {
	Payload *models.IoK8sAPIBatchV1Job
}

func (o *ReadBatchV1NamespacedJobOK) Error() string {
	return fmt.Sprintf("[GET /apis/batch/v1/namespaces/{namespace}/jobs/{name}][%d] readBatchV1NamespacedJobOK  %+v", 200, o.Payload)
}

func (o *ReadBatchV1NamespacedJobOK) GetPayload() *models.IoK8sAPIBatchV1Job {
	return o.Payload
}

func (o *ReadBatchV1NamespacedJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPIBatchV1Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadBatchV1NamespacedJobUnauthorized creates a ReadBatchV1NamespacedJobUnauthorized with default headers values
func NewReadBatchV1NamespacedJobUnauthorized() *ReadBatchV1NamespacedJobUnauthorized {
	return &ReadBatchV1NamespacedJobUnauthorized{}
}

/*ReadBatchV1NamespacedJobUnauthorized handles this case with default header values.

Unauthorized
*/
type ReadBatchV1NamespacedJobUnauthorized struct {
}

func (o *ReadBatchV1NamespacedJobUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/batch/v1/namespaces/{namespace}/jobs/{name}][%d] readBatchV1NamespacedJobUnauthorized ", 401)
}

func (o *ReadBatchV1NamespacedJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
