---
info:
  title: Management
  version: unversioned
swagger: '2.0'
produces:
  - application/json
consumes:
  - application/json
paths:
  "/management/kubernetes.io/v1/pods":
    post:
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
      schemes:
      - http
      tags:
      - cilium
      parameters:
        - "$ref": "#/parameters/options"
      operationId: "PostManagementKubernetesIoV1Pods"
  "/management/cilium.io/v2/ciliumendpoints":
    post:
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
      schemes:
      - http
      tags:
      - cilium
      parameters:
        - "$ref": "#/parameters/options"
      operationId: "PostManagementCiliumIoV2CiliumEndpoints"
  "/management/cilium.io/v2/ciliumnodes":
    post:
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
      schemes:
      - http
      tags:
      - cilium
      parameters:
        - "$ref": "#/parameters/options"
      operationId: "PostManagementCiliumIoV2CiliumNodes"
  "/management/cilium.io/v2/ciliumidentities":
    post:
      responses:
        '200':
          description: OK
        '202':
          description: Accepted
      schemes:
      - http
      tags:
      - cilium
      parameters:
        - "$ref": "#/parameters/options"
      operationId: "PostManagementCiliumIoV2CiliumIdentities"
definitions:
  add:
    description: add N random new Objects
    type: integer
  del:
    description: del N random new Objects
    type: integer
  dependents:
    description: if possible, create dependent Objects
    type: boolean
  options:
    type: object
    properties:
      add:
        "$ref": "#/definitions/add"
      del:
        "$ref": "#/definitions/del"
      with-dependents:
        "$ref": "#/definitions/dependents"

parameters:
  options:
    name: options
    in: body
    description: Options to modify structures
    schema:
      "$ref": "#/definitions/options"
