// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package certificates_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchCertificatesV1beta1CertificateSigningRequestApprovalHandlerFunc turns a function with the right signature into a patch certificates v1beta1 certificate signing request approval handler
type PatchCertificatesV1beta1CertificateSigningRequestApprovalHandlerFunc func(PatchCertificatesV1beta1CertificateSigningRequestApprovalParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchCertificatesV1beta1CertificateSigningRequestApprovalHandlerFunc) Handle(params PatchCertificatesV1beta1CertificateSigningRequestApprovalParams) middleware.Responder {
	return fn(params)
}

// PatchCertificatesV1beta1CertificateSigningRequestApprovalHandler interface for that can handle valid patch certificates v1beta1 certificate signing request approval params
type PatchCertificatesV1beta1CertificateSigningRequestApprovalHandler interface {
	Handle(PatchCertificatesV1beta1CertificateSigningRequestApprovalParams) middleware.Responder
}

// NewPatchCertificatesV1beta1CertificateSigningRequestApproval creates a new http.Handler for the patch certificates v1beta1 certificate signing request approval operation
func NewPatchCertificatesV1beta1CertificateSigningRequestApproval(ctx *middleware.Context, handler PatchCertificatesV1beta1CertificateSigningRequestApprovalHandler) *PatchCertificatesV1beta1CertificateSigningRequestApproval {
	return &PatchCertificatesV1beta1CertificateSigningRequestApproval{Context: ctx, Handler: handler}
}

/*PatchCertificatesV1beta1CertificateSigningRequestApproval swagger:route PATCH /apis/certificates.k8s.io/v1beta1/certificatesigningrequests/{name}/approval certificates_v1beta1 patchCertificatesV1beta1CertificateSigningRequestApproval

partially update approval of the specified CertificateSigningRequest

*/
type PatchCertificatesV1beta1CertificateSigningRequestApproval struct {
	Context *middleware.Context
	Handler PatchCertificatesV1beta1CertificateSigningRequestApprovalHandler
}

func (o *PatchCertificatesV1beta1CertificateSigningRequestApproval) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchCertificatesV1beta1CertificateSigningRequestApprovalParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
