// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCodeVersionHandlerFunc turns a function with the right signature into a get code version handler
type GetCodeVersionHandlerFunc func(GetCodeVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCodeVersionHandlerFunc) Handle(params GetCodeVersionParams) middleware.Responder {
	return fn(params)
}

// GetCodeVersionHandler interface for that can handle valid get code version params
type GetCodeVersionHandler interface {
	Handle(GetCodeVersionParams) middleware.Responder
}

// NewGetCodeVersion creates a new http.Handler for the get code version operation
func NewGetCodeVersion(ctx *middleware.Context, handler GetCodeVersionHandler) *GetCodeVersion {
	return &GetCodeVersion{Context: ctx, Handler: handler}
}

/*GetCodeVersion swagger:route GET /version/ version getCodeVersion

get the code version

*/
type GetCodeVersion struct {
	Context *middleware.Context
	Handler GetCodeVersionHandler
}

func (o *GetCodeVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCodeVersionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
