// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// GetCertificatesAPIGroupReader is a Reader for the GetCertificatesAPIGroup structure.
type GetCertificatesAPIGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCertificatesAPIGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCertificatesAPIGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCertificatesAPIGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCertificatesAPIGroupOK creates a GetCertificatesAPIGroupOK with default headers values
func NewGetCertificatesAPIGroupOK() *GetCertificatesAPIGroupOK {
	return &GetCertificatesAPIGroupOK{}
}

/*GetCertificatesAPIGroupOK handles this case with default header values.

OK
*/
type GetCertificatesAPIGroupOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup
}

func (o *GetCertificatesAPIGroupOK) Error() string {
	return fmt.Sprintf("[GET /apis/certificates.k8s.io/][%d] getCertificatesApiGroupOK  %+v", 200, o.Payload)
}

func (o *GetCertificatesAPIGroupOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1APIGroup {
	return o.Payload
}

func (o *GetCertificatesAPIGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1APIGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCertificatesAPIGroupUnauthorized creates a GetCertificatesAPIGroupUnauthorized with default headers values
func NewGetCertificatesAPIGroupUnauthorized() *GetCertificatesAPIGroupUnauthorized {
	return &GetCertificatesAPIGroupUnauthorized{}
}

/*GetCertificatesAPIGroupUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCertificatesAPIGroupUnauthorized struct {
}

func (o *GetCertificatesAPIGroupUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/certificates.k8s.io/][%d] getCertificatesApiGroupUnauthorized ", 401)
}

func (o *GetCertificatesAPIGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
