// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package autoscaling_v2beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOKCode is the HTTP code returned for type WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK
const WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOKCode int = 200

/*WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK OK

swagger:response watchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK
*/
type WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent `json:"body,omitempty"`
}

// NewWatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK creates WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK with default headers values
func NewWatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK() *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK {

	return &WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK{}
}

// WithPayload adds the payload to the watch autoscaling v2beta1 namespaced horizontal pod autoscaler list o k response
func (o *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the watch autoscaling v2beta1 namespaced horizontal pod autoscaler list o k response
func (o *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorizedCode is the HTTP code returned for type WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized
const WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorizedCode int = 401

/*WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized Unauthorized

swagger:response watchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized
*/
type WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized struct {
}

// NewWatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized creates WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized with default headers values
func NewWatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized() *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized {

	return &WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized{}
}

// WriteResponse to the client
func (o *WatchAutoscalingV2beta1NamespacedHorizontalPodAutoscalerListUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
