// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package node_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ListNodeV1beta1RuntimeClassOKCode is the HTTP code returned for type ListNodeV1beta1RuntimeClassOK
const ListNodeV1beta1RuntimeClassOKCode int = 200

/*ListNodeV1beta1RuntimeClassOK OK

swagger:response listNodeV1beta1RuntimeClassOK
*/
type ListNodeV1beta1RuntimeClassOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPINodeV1beta1RuntimeClassList `json:"body,omitempty"`
}

// NewListNodeV1beta1RuntimeClassOK creates ListNodeV1beta1RuntimeClassOK with default headers values
func NewListNodeV1beta1RuntimeClassOK() *ListNodeV1beta1RuntimeClassOK {

	return &ListNodeV1beta1RuntimeClassOK{}
}

// WithPayload adds the payload to the list node v1beta1 runtime class o k response
func (o *ListNodeV1beta1RuntimeClassOK) WithPayload(payload *models.IoK8sAPINodeV1beta1RuntimeClassList) *ListNodeV1beta1RuntimeClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list node v1beta1 runtime class o k response
func (o *ListNodeV1beta1RuntimeClassOK) SetPayload(payload *models.IoK8sAPINodeV1beta1RuntimeClassList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListNodeV1beta1RuntimeClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListNodeV1beta1RuntimeClassUnauthorizedCode is the HTTP code returned for type ListNodeV1beta1RuntimeClassUnauthorized
const ListNodeV1beta1RuntimeClassUnauthorizedCode int = 401

/*ListNodeV1beta1RuntimeClassUnauthorized Unauthorized

swagger:response listNodeV1beta1RuntimeClassUnauthorized
*/
type ListNodeV1beta1RuntimeClassUnauthorized struct {
}

// NewListNodeV1beta1RuntimeClassUnauthorized creates ListNodeV1beta1RuntimeClassUnauthorized with default headers values
func NewListNodeV1beta1RuntimeClassUnauthorized() *ListNodeV1beta1RuntimeClassUnauthorized {

	return &ListNodeV1beta1RuntimeClassUnauthorized{}
}

// WriteResponse to the client
func (o *ListNodeV1beta1RuntimeClassUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
