// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package rbac_authorization_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchRbacAuthorizationV1ClusterRoleOKCode is the HTTP code returned for type WatchRbacAuthorizationV1ClusterRoleOK
const WatchRbacAuthorizationV1ClusterRoleOKCode int = 200

/*WatchRbacAuthorizationV1ClusterRoleOK OK

swagger:response watchRbacAuthorizationV1ClusterRoleOK
*/
type WatchRbacAuthorizationV1ClusterRoleOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent `json:"body,omitempty"`
}

// NewWatchRbacAuthorizationV1ClusterRoleOK creates WatchRbacAuthorizationV1ClusterRoleOK with default headers values
func NewWatchRbacAuthorizationV1ClusterRoleOK() *WatchRbacAuthorizationV1ClusterRoleOK {

	return &WatchRbacAuthorizationV1ClusterRoleOK{}
}

// WithPayload adds the payload to the watch rbac authorization v1 cluster role o k response
func (o *WatchRbacAuthorizationV1ClusterRoleOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) *WatchRbacAuthorizationV1ClusterRoleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the watch rbac authorization v1 cluster role o k response
func (o *WatchRbacAuthorizationV1ClusterRoleOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WatchRbacAuthorizationV1ClusterRoleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WatchRbacAuthorizationV1ClusterRoleUnauthorizedCode is the HTTP code returned for type WatchRbacAuthorizationV1ClusterRoleUnauthorized
const WatchRbacAuthorizationV1ClusterRoleUnauthorizedCode int = 401

/*WatchRbacAuthorizationV1ClusterRoleUnauthorized Unauthorized

swagger:response watchRbacAuthorizationV1ClusterRoleUnauthorized
*/
type WatchRbacAuthorizationV1ClusterRoleUnauthorized struct {
}

// NewWatchRbacAuthorizationV1ClusterRoleUnauthorized creates WatchRbacAuthorizationV1ClusterRoleUnauthorized with default headers values
func NewWatchRbacAuthorizationV1ClusterRoleUnauthorized() *WatchRbacAuthorizationV1ClusterRoleUnauthorized {

	return &WatchRbacAuthorizationV1ClusterRoleUnauthorized{}
}

// WriteResponse to the client
func (o *WatchRbacAuthorizationV1ClusterRoleUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
