// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package flowcontrol_apiserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// GetFlowcontrolApiserverAPIGroupOKCode is the HTTP code returned for type GetFlowcontrolApiserverAPIGroupOK
const GetFlowcontrolApiserverAPIGroupOKCode int = 200

/*GetFlowcontrolApiserverAPIGroupOK OK

swagger:response getFlowcontrolApiserverApiGroupOK
*/
type GetFlowcontrolApiserverAPIGroupOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup `json:"body,omitempty"`
}

// NewGetFlowcontrolApiserverAPIGroupOK creates GetFlowcontrolApiserverAPIGroupOK with default headers values
func NewGetFlowcontrolApiserverAPIGroupOK() *GetFlowcontrolApiserverAPIGroupOK {

	return &GetFlowcontrolApiserverAPIGroupOK{}
}

// WithPayload adds the payload to the get flowcontrol apiserver Api group o k response
func (o *GetFlowcontrolApiserverAPIGroupOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup) *GetFlowcontrolApiserverAPIGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get flowcontrol apiserver Api group o k response
func (o *GetFlowcontrolApiserverAPIGroupOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1APIGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFlowcontrolApiserverAPIGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFlowcontrolApiserverAPIGroupUnauthorizedCode is the HTTP code returned for type GetFlowcontrolApiserverAPIGroupUnauthorized
const GetFlowcontrolApiserverAPIGroupUnauthorizedCode int = 401

/*GetFlowcontrolApiserverAPIGroupUnauthorized Unauthorized

swagger:response getFlowcontrolApiserverApiGroupUnauthorized
*/
type GetFlowcontrolApiserverAPIGroupUnauthorized struct {
}

// NewGetFlowcontrolApiserverAPIGroupUnauthorized creates GetFlowcontrolApiserverAPIGroupUnauthorized with default headers values
func NewGetFlowcontrolApiserverAPIGroupUnauthorized() *GetFlowcontrolApiserverAPIGroupUnauthorized {

	return &GetFlowcontrolApiserverAPIGroupUnauthorized{}
}

// WriteResponse to the client
func (o *GetFlowcontrolApiserverAPIGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
