// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package storage_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReplaceStorageV1beta1StorageClassOKCode is the HTTP code returned for type ReplaceStorageV1beta1StorageClassOK
const ReplaceStorageV1beta1StorageClassOKCode int = 200

/*ReplaceStorageV1beta1StorageClassOK OK

swagger:response replaceStorageV1beta1StorageClassOK
*/
type ReplaceStorageV1beta1StorageClassOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIStorageV1beta1StorageClass `json:"body,omitempty"`
}

// NewReplaceStorageV1beta1StorageClassOK creates ReplaceStorageV1beta1StorageClassOK with default headers values
func NewReplaceStorageV1beta1StorageClassOK() *ReplaceStorageV1beta1StorageClassOK {

	return &ReplaceStorageV1beta1StorageClassOK{}
}

// WithPayload adds the payload to the replace storage v1beta1 storage class o k response
func (o *ReplaceStorageV1beta1StorageClassOK) WithPayload(payload *models.IoK8sAPIStorageV1beta1StorageClass) *ReplaceStorageV1beta1StorageClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace storage v1beta1 storage class o k response
func (o *ReplaceStorageV1beta1StorageClassOK) SetPayload(payload *models.IoK8sAPIStorageV1beta1StorageClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceStorageV1beta1StorageClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceStorageV1beta1StorageClassCreatedCode is the HTTP code returned for type ReplaceStorageV1beta1StorageClassCreated
const ReplaceStorageV1beta1StorageClassCreatedCode int = 201

/*ReplaceStorageV1beta1StorageClassCreated Created

swagger:response replaceStorageV1beta1StorageClassCreated
*/
type ReplaceStorageV1beta1StorageClassCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIStorageV1beta1StorageClass `json:"body,omitempty"`
}

// NewReplaceStorageV1beta1StorageClassCreated creates ReplaceStorageV1beta1StorageClassCreated with default headers values
func NewReplaceStorageV1beta1StorageClassCreated() *ReplaceStorageV1beta1StorageClassCreated {

	return &ReplaceStorageV1beta1StorageClassCreated{}
}

// WithPayload adds the payload to the replace storage v1beta1 storage class created response
func (o *ReplaceStorageV1beta1StorageClassCreated) WithPayload(payload *models.IoK8sAPIStorageV1beta1StorageClass) *ReplaceStorageV1beta1StorageClassCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace storage v1beta1 storage class created response
func (o *ReplaceStorageV1beta1StorageClassCreated) SetPayload(payload *models.IoK8sAPIStorageV1beta1StorageClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceStorageV1beta1StorageClassCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceStorageV1beta1StorageClassUnauthorizedCode is the HTTP code returned for type ReplaceStorageV1beta1StorageClassUnauthorized
const ReplaceStorageV1beta1StorageClassUnauthorizedCode int = 401

/*ReplaceStorageV1beta1StorageClassUnauthorized Unauthorized

swagger:response replaceStorageV1beta1StorageClassUnauthorized
*/
type ReplaceStorageV1beta1StorageClassUnauthorized struct {
}

// NewReplaceStorageV1beta1StorageClassUnauthorized creates ReplaceStorageV1beta1StorageClassUnauthorized with default headers values
func NewReplaceStorageV1beta1StorageClassUnauthorized() *ReplaceStorageV1beta1StorageClassUnauthorized {

	return &ReplaceStorageV1beta1StorageClassUnauthorized{}
}

// WriteResponse to the client
func (o *ReplaceStorageV1beta1StorageClassUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
