// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package autoscaling_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListReader is a Reader for the WatchAutoscalingV1NamespacedHorizontalPodAutoscalerList structure.
type WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK creates a WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK with default headers values
func NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK() *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK {
	return &WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK{}
}

/*WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK handles this case with default header values.

OK
*/
type WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK) Error() string {
	return fmt.Sprintf("[GET /apis/autoscaling/v1/watch/namespaces/{namespace}/horizontalpodautoscalers][%d] watchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK  %+v", 200, o.Payload)
}

func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized creates a WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized with default headers values
func NewWatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized() *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized {
	return &WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized{}
}

/*WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized struct {
}

func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/autoscaling/v1/watch/namespaces/{namespace}/horizontalpodautoscalers][%d] watchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized ", 401)
}

func (o *WatchAutoscalingV1NamespacedHorizontalPodAutoscalerListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
