// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// PatchStorageV1VolumeAttachmentStatusReader is a Reader for the PatchStorageV1VolumeAttachmentStatus structure.
type PatchStorageV1VolumeAttachmentStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchStorageV1VolumeAttachmentStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchStorageV1VolumeAttachmentStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPatchStorageV1VolumeAttachmentStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchStorageV1VolumeAttachmentStatusOK creates a PatchStorageV1VolumeAttachmentStatusOK with default headers values
func NewPatchStorageV1VolumeAttachmentStatusOK() *PatchStorageV1VolumeAttachmentStatusOK {
	return &PatchStorageV1VolumeAttachmentStatusOK{}
}

/*PatchStorageV1VolumeAttachmentStatusOK handles this case with default header values.

OK
*/
type PatchStorageV1VolumeAttachmentStatusOK struct {
	Payload *models.IoK8sAPIStorageV1VolumeAttachment
}

func (o *PatchStorageV1VolumeAttachmentStatusOK) Error() string {
	return fmt.Sprintf("[PATCH /apis/storage.k8s.io/v1/volumeattachments/{name}/status][%d] patchStorageV1VolumeAttachmentStatusOK  %+v", 200, o.Payload)
}

func (o *PatchStorageV1VolumeAttachmentStatusOK) GetPayload() *models.IoK8sAPIStorageV1VolumeAttachment {
	return o.Payload
}

func (o *PatchStorageV1VolumeAttachmentStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPIStorageV1VolumeAttachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchStorageV1VolumeAttachmentStatusUnauthorized creates a PatchStorageV1VolumeAttachmentStatusUnauthorized with default headers values
func NewPatchStorageV1VolumeAttachmentStatusUnauthorized() *PatchStorageV1VolumeAttachmentStatusUnauthorized {
	return &PatchStorageV1VolumeAttachmentStatusUnauthorized{}
}

/*PatchStorageV1VolumeAttachmentStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type PatchStorageV1VolumeAttachmentStatusUnauthorized struct {
}

func (o *PatchStorageV1VolumeAttachmentStatusUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /apis/storage.k8s.io/v1/volumeattachments/{name}/status][%d] patchStorageV1VolumeAttachmentStatusUnauthorized ", 401)
}

func (o *PatchStorageV1VolumeAttachmentStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
