// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package storage_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchStorageV1VolumeAttachmentReader is a Reader for the WatchStorageV1VolumeAttachment structure.
type WatchStorageV1VolumeAttachmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchStorageV1VolumeAttachmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchStorageV1VolumeAttachmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchStorageV1VolumeAttachmentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchStorageV1VolumeAttachmentOK creates a WatchStorageV1VolumeAttachmentOK with default headers values
func NewWatchStorageV1VolumeAttachmentOK() *WatchStorageV1VolumeAttachmentOK {
	return &WatchStorageV1VolumeAttachmentOK{}
}

/*WatchStorageV1VolumeAttachmentOK handles this case with default header values.

OK
*/
type WatchStorageV1VolumeAttachmentOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchStorageV1VolumeAttachmentOK) Error() string {
	return fmt.Sprintf("[GET /apis/storage.k8s.io/v1/watch/volumeattachments/{name}][%d] watchStorageV1VolumeAttachmentOK  %+v", 200, o.Payload)
}

func (o *WatchStorageV1VolumeAttachmentOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchStorageV1VolumeAttachmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchStorageV1VolumeAttachmentUnauthorized creates a WatchStorageV1VolumeAttachmentUnauthorized with default headers values
func NewWatchStorageV1VolumeAttachmentUnauthorized() *WatchStorageV1VolumeAttachmentUnauthorized {
	return &WatchStorageV1VolumeAttachmentUnauthorized{}
}

/*WatchStorageV1VolumeAttachmentUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchStorageV1VolumeAttachmentUnauthorized struct {
}

func (o *WatchStorageV1VolumeAttachmentUnauthorized) Error() string {
	return fmt.Sprintf("[GET /apis/storage.k8s.io/v1/watch/volumeattachments/{name}][%d] watchStorageV1VolumeAttachmentUnauthorized ", 401)
}

func (o *WatchStorageV1VolumeAttachmentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
