// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package extensions_v1beta1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReplaceExtensionsV1beta1NamespacedIngressHandlerFunc turns a function with the right signature into a replace extensions v1beta1 namespaced ingress handler
type ReplaceExtensionsV1beta1NamespacedIngressHandlerFunc func(ReplaceExtensionsV1beta1NamespacedIngressParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReplaceExtensionsV1beta1NamespacedIngressHandlerFunc) Handle(params ReplaceExtensionsV1beta1NamespacedIngressParams) middleware.Responder {
	return fn(params)
}

// ReplaceExtensionsV1beta1NamespacedIngressHandler interface for that can handle valid replace extensions v1beta1 namespaced ingress params
type ReplaceExtensionsV1beta1NamespacedIngressHandler interface {
	Handle(ReplaceExtensionsV1beta1NamespacedIngressParams) middleware.Responder
}

// NewReplaceExtensionsV1beta1NamespacedIngress creates a new http.Handler for the replace extensions v1beta1 namespaced ingress operation
func NewReplaceExtensionsV1beta1NamespacedIngress(ctx *middleware.Context, handler ReplaceExtensionsV1beta1NamespacedIngressHandler) *ReplaceExtensionsV1beta1NamespacedIngress {
	return &ReplaceExtensionsV1beta1NamespacedIngress{Context: ctx, Handler: handler}
}

/*ReplaceExtensionsV1beta1NamespacedIngress swagger:route PUT /apis/extensions/v1beta1/namespaces/{namespace}/ingresses/{name} extensions_v1beta1 replaceExtensionsV1beta1NamespacedIngress

replace the specified Ingress

*/
type ReplaceExtensionsV1beta1NamespacedIngress struct {
	Context *middleware.Context
	Handler ReplaceExtensionsV1beta1NamespacedIngressHandler
}

func (o *ReplaceExtensionsV1beta1NamespacedIngress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReplaceExtensionsV1beta1NamespacedIngressParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
