// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ConnectCoreV1PutNodeProxyReader is a Reader for the ConnectCoreV1PutNodeProxy structure.
type ConnectCoreV1PutNodeProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConnectCoreV1PutNodeProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConnectCoreV1PutNodeProxyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewConnectCoreV1PutNodeProxyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConnectCoreV1PutNodeProxyOK creates a ConnectCoreV1PutNodeProxyOK with default headers values
func NewConnectCoreV1PutNodeProxyOK() *ConnectCoreV1PutNodeProxyOK {
	return &ConnectCoreV1PutNodeProxyOK{}
}

/*ConnectCoreV1PutNodeProxyOK handles this case with default header values.

OK
*/
type ConnectCoreV1PutNodeProxyOK struct {
	Payload string
}

func (o *ConnectCoreV1PutNodeProxyOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/nodes/{name}/proxy][%d] connectCoreV1PutNodeProxyOK  %+v", 200, o.Payload)
}

func (o *ConnectCoreV1PutNodeProxyOK) GetPayload() string {
	return o.Payload
}

func (o *ConnectCoreV1PutNodeProxyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConnectCoreV1PutNodeProxyUnauthorized creates a ConnectCoreV1PutNodeProxyUnauthorized with default headers values
func NewConnectCoreV1PutNodeProxyUnauthorized() *ConnectCoreV1PutNodeProxyUnauthorized {
	return &ConnectCoreV1PutNodeProxyUnauthorized{}
}

/*ConnectCoreV1PutNodeProxyUnauthorized handles this case with default header values.

Unauthorized
*/
type ConnectCoreV1PutNodeProxyUnauthorized struct {
}

func (o *ConnectCoreV1PutNodeProxyUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v1/nodes/{name}/proxy][%d] connectCoreV1PutNodeProxyUnauthorized ", 401)
}

func (o *ConnectCoreV1PutNodeProxyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
