// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ConnectCoreV1GetNamespacedPodAttachReader is a Reader for the ConnectCoreV1GetNamespacedPodAttach structure.
type ConnectCoreV1GetNamespacedPodAttachReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConnectCoreV1GetNamespacedPodAttachReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConnectCoreV1GetNamespacedPodAttachOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewConnectCoreV1GetNamespacedPodAttachUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConnectCoreV1GetNamespacedPodAttachOK creates a ConnectCoreV1GetNamespacedPodAttachOK with default headers values
func NewConnectCoreV1GetNamespacedPodAttachOK() *ConnectCoreV1GetNamespacedPodAttachOK {
	return &ConnectCoreV1GetNamespacedPodAttachOK{}
}

/*ConnectCoreV1GetNamespacedPodAttachOK handles this case with default header values.

OK
*/
type ConnectCoreV1GetNamespacedPodAttachOK struct {
	Payload string
}

func (o *ConnectCoreV1GetNamespacedPodAttachOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/namespaces/{namespace}/pods/{name}/attach][%d] connectCoreV1GetNamespacedPodAttachOK  %+v", 200, o.Payload)
}

func (o *ConnectCoreV1GetNamespacedPodAttachOK) GetPayload() string {
	return o.Payload
}

func (o *ConnectCoreV1GetNamespacedPodAttachOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConnectCoreV1GetNamespacedPodAttachUnauthorized creates a ConnectCoreV1GetNamespacedPodAttachUnauthorized with default headers values
func NewConnectCoreV1GetNamespacedPodAttachUnauthorized() *ConnectCoreV1GetNamespacedPodAttachUnauthorized {
	return &ConnectCoreV1GetNamespacedPodAttachUnauthorized{}
}

/*ConnectCoreV1GetNamespacedPodAttachUnauthorized handles this case with default header values.

Unauthorized
*/
type ConnectCoreV1GetNamespacedPodAttachUnauthorized struct {
}

func (o *ConnectCoreV1GetNamespacedPodAttachUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/namespaces/{namespace}/pods/{name}/attach][%d] connectCoreV1GetNamespacedPodAttachUnauthorized ", 401)
}

func (o *ConnectCoreV1GetNamespacedPodAttachUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
