// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// NewCreateCoreV1NamespacedReplicationControllerParams creates a new CreateCoreV1NamespacedReplicationControllerParams object
// with the default values initialized.
func NewCreateCoreV1NamespacedReplicationControllerParams() *CreateCoreV1NamespacedReplicationControllerParams {
	var ()
	return &CreateCoreV1NamespacedReplicationControllerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCoreV1NamespacedReplicationControllerParamsWithTimeout creates a new CreateCoreV1NamespacedReplicationControllerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCoreV1NamespacedReplicationControllerParamsWithTimeout(timeout time.Duration) *CreateCoreV1NamespacedReplicationControllerParams {
	var ()
	return &CreateCoreV1NamespacedReplicationControllerParams{

		timeout: timeout,
	}
}

// NewCreateCoreV1NamespacedReplicationControllerParamsWithContext creates a new CreateCoreV1NamespacedReplicationControllerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCoreV1NamespacedReplicationControllerParamsWithContext(ctx context.Context) *CreateCoreV1NamespacedReplicationControllerParams {
	var ()
	return &CreateCoreV1NamespacedReplicationControllerParams{

		Context: ctx,
	}
}

// NewCreateCoreV1NamespacedReplicationControllerParamsWithHTTPClient creates a new CreateCoreV1NamespacedReplicationControllerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCoreV1NamespacedReplicationControllerParamsWithHTTPClient(client *http.Client) *CreateCoreV1NamespacedReplicationControllerParams {
	var ()
	return &CreateCoreV1NamespacedReplicationControllerParams{
		HTTPClient: client,
	}
}

/*CreateCoreV1NamespacedReplicationControllerParams contains all the parameters to send to the API endpoint
for the create core v1 namespaced replication controller operation typically these are written to a http.Request
*/
type CreateCoreV1NamespacedReplicationControllerParams struct {

	/*Body*/
	Body *models.IoK8sAPICoreV1ReplicationController
	/*DryRun
	  When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed

	*/
	DryRun *string
	/*FieldManager
	  fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.

	*/
	FieldManager *string
	/*Namespace
	  object name and auth scope, such as for teams and projects

	*/
	Namespace string
	/*Pretty
	  If 'true', then the output is pretty printed.

	*/
	Pretty *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithTimeout(timeout time.Duration) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithContext(ctx context.Context) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithHTTPClient(client *http.Client) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithBody(body *models.IoK8sAPICoreV1ReplicationController) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetBody(body *models.IoK8sAPICoreV1ReplicationController) {
	o.Body = body
}

// WithDryRun adds the dryRun to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithDryRun(dryRun *string) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetDryRun(dryRun)
	return o
}

// SetDryRun adds the dryRun to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetDryRun(dryRun *string) {
	o.DryRun = dryRun
}

// WithFieldManager adds the fieldManager to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithFieldManager(fieldManager *string) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetFieldManager(fieldManager)
	return o
}

// SetFieldManager adds the fieldManager to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetFieldManager(fieldManager *string) {
	o.FieldManager = fieldManager
}

// WithNamespace adds the namespace to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithNamespace(namespace string) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPretty adds the pretty to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) WithPretty(pretty *string) *CreateCoreV1NamespacedReplicationControllerParams {
	o.SetPretty(pretty)
	return o
}

// SetPretty adds the pretty to the create core v1 namespaced replication controller params
func (o *CreateCoreV1NamespacedReplicationControllerParams) SetPretty(pretty *string) {
	o.Pretty = pretty
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCoreV1NamespacedReplicationControllerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.DryRun != nil {

		// query param dryRun
		var qrDryRun string
		if o.DryRun != nil {
			qrDryRun = *o.DryRun
		}
		qDryRun := qrDryRun
		if qDryRun != "" {
			if err := r.SetQueryParam("dryRun", qDryRun); err != nil {
				return err
			}
		}

	}

	if o.FieldManager != nil {

		// query param fieldManager
		var qrFieldManager string
		if o.FieldManager != nil {
			qrFieldManager = *o.FieldManager
		}
		qFieldManager := qrFieldManager
		if qFieldManager != "" {
			if err := r.SetQueryParam("fieldManager", qFieldManager); err != nil {
				return err
			}
		}

	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Pretty != nil {

		// query param pretty
		var qrPretty string
		if o.Pretty != nil {
			qrPretty = *o.Pretty
		}
		qPretty := qrPretty
		if qPretty != "" {
			if err := r.SetQueryParam("pretty", qPretty); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
