// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewReadCoreV1NodeParams creates a new ReadCoreV1NodeParams object
// with the default values initialized.
func NewReadCoreV1NodeParams() *ReadCoreV1NodeParams {
	var ()
	return &ReadCoreV1NodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadCoreV1NodeParamsWithTimeout creates a new ReadCoreV1NodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadCoreV1NodeParamsWithTimeout(timeout time.Duration) *ReadCoreV1NodeParams {
	var ()
	return &ReadCoreV1NodeParams{

		timeout: timeout,
	}
}

// NewReadCoreV1NodeParamsWithContext creates a new ReadCoreV1NodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadCoreV1NodeParamsWithContext(ctx context.Context) *ReadCoreV1NodeParams {
	var ()
	return &ReadCoreV1NodeParams{

		Context: ctx,
	}
}

// NewReadCoreV1NodeParamsWithHTTPClient creates a new ReadCoreV1NodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadCoreV1NodeParamsWithHTTPClient(client *http.Client) *ReadCoreV1NodeParams {
	var ()
	return &ReadCoreV1NodeParams{
		HTTPClient: client,
	}
}

/*ReadCoreV1NodeParams contains all the parameters to send to the API endpoint
for the read core v1 node operation typically these are written to a http.Request
*/
type ReadCoreV1NodeParams struct {

	/*Exact
	  Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'. Deprecated. Planned for removal in 1.18.

	*/
	Exact *bool
	/*Export
	  Should this value be exported.  Export strips fields that a user can not specify. Deprecated. Planned for removal in 1.18.

	*/
	Export *bool
	/*Name
	  name of the Node

	*/
	Name string
	/*Pretty
	  If 'true', then the output is pretty printed.

	*/
	Pretty *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithTimeout(timeout time.Duration) *ReadCoreV1NodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithContext(ctx context.Context) *ReadCoreV1NodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithHTTPClient(client *http.Client) *ReadCoreV1NodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExact adds the exact to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithExact(exact *bool) *ReadCoreV1NodeParams {
	o.SetExact(exact)
	return o
}

// SetExact adds the exact to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetExact(exact *bool) {
	o.Exact = exact
}

// WithExport adds the export to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithExport(export *bool) *ReadCoreV1NodeParams {
	o.SetExport(export)
	return o
}

// SetExport adds the export to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetExport(export *bool) {
	o.Export = export
}

// WithName adds the name to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithName(name string) *ReadCoreV1NodeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetName(name string) {
	o.Name = name
}

// WithPretty adds the pretty to the read core v1 node params
func (o *ReadCoreV1NodeParams) WithPretty(pretty *string) *ReadCoreV1NodeParams {
	o.SetPretty(pretty)
	return o
}

// SetPretty adds the pretty to the read core v1 node params
func (o *ReadCoreV1NodeParams) SetPretty(pretty *string) {
	o.Pretty = pretty
}

// WriteToRequest writes these params to a swagger request
func (o *ReadCoreV1NodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exact != nil {

		// query param exact
		var qrExact bool
		if o.Exact != nil {
			qrExact = *o.Exact
		}
		qExact := swag.FormatBool(qrExact)
		if qExact != "" {
			if err := r.SetQueryParam("exact", qExact); err != nil {
				return err
			}
		}

	}

	if o.Export != nil {

		// query param export
		var qrExport bool
		if o.Export != nil {
			qrExport = *o.Export
		}
		qExport := swag.FormatBool(qrExport)
		if qExport != "" {
			if err := r.SetQueryParam("export", qExport); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Pretty != nil {

		// query param pretty
		var qrPretty string
		if o.Pretty != nil {
			qrPretty = *o.Pretty
		}
		qPretty := qrPretty
		if qPretty != "" {
			if err := r.SetQueryParam("pretty", qPretty); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
