// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReplaceCoreV1NamespacedServiceReader is a Reader for the ReplaceCoreV1NamespacedService structure.
type ReplaceCoreV1NamespacedServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceCoreV1NamespacedServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceCoreV1NamespacedServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewReplaceCoreV1NamespacedServiceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewReplaceCoreV1NamespacedServiceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReplaceCoreV1NamespacedServiceOK creates a ReplaceCoreV1NamespacedServiceOK with default headers values
func NewReplaceCoreV1NamespacedServiceOK() *ReplaceCoreV1NamespacedServiceOK {
	return &ReplaceCoreV1NamespacedServiceOK{}
}

/*ReplaceCoreV1NamespacedServiceOK handles this case with default header values.

OK
*/
type ReplaceCoreV1NamespacedServiceOK struct {
	Payload *models.IoK8sAPICoreV1Service
}

func (o *ReplaceCoreV1NamespacedServiceOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/services/{name}][%d] replaceCoreV1NamespacedServiceOK  %+v", 200, o.Payload)
}

func (o *ReplaceCoreV1NamespacedServiceOK) GetPayload() *models.IoK8sAPICoreV1Service {
	return o.Payload
}

func (o *ReplaceCoreV1NamespacedServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPICoreV1Service)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCoreV1NamespacedServiceCreated creates a ReplaceCoreV1NamespacedServiceCreated with default headers values
func NewReplaceCoreV1NamespacedServiceCreated() *ReplaceCoreV1NamespacedServiceCreated {
	return &ReplaceCoreV1NamespacedServiceCreated{}
}

/*ReplaceCoreV1NamespacedServiceCreated handles this case with default header values.

Created
*/
type ReplaceCoreV1NamespacedServiceCreated struct {
	Payload *models.IoK8sAPICoreV1Service
}

func (o *ReplaceCoreV1NamespacedServiceCreated) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/services/{name}][%d] replaceCoreV1NamespacedServiceCreated  %+v", 201, o.Payload)
}

func (o *ReplaceCoreV1NamespacedServiceCreated) GetPayload() *models.IoK8sAPICoreV1Service {
	return o.Payload
}

func (o *ReplaceCoreV1NamespacedServiceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPICoreV1Service)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCoreV1NamespacedServiceUnauthorized creates a ReplaceCoreV1NamespacedServiceUnauthorized with default headers values
func NewReplaceCoreV1NamespacedServiceUnauthorized() *ReplaceCoreV1NamespacedServiceUnauthorized {
	return &ReplaceCoreV1NamespacedServiceUnauthorized{}
}

/*ReplaceCoreV1NamespacedServiceUnauthorized handles this case with default header values.

Unauthorized
*/
type ReplaceCoreV1NamespacedServiceUnauthorized struct {
}

func (o *ReplaceCoreV1NamespacedServiceUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/services/{name}][%d] replaceCoreV1NamespacedServiceUnauthorized ", 401)
}

func (o *ReplaceCoreV1NamespacedServiceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
