// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ReplaceCoreV1NamespacedResourceQuotaStatusReader is a Reader for the ReplaceCoreV1NamespacedResourceQuotaStatus structure.
type ReplaceCoreV1NamespacedResourceQuotaStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceCoreV1NamespacedResourceQuotaStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceCoreV1NamespacedResourceQuotaStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewReplaceCoreV1NamespacedResourceQuotaStatusCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReplaceCoreV1NamespacedResourceQuotaStatusOK creates a ReplaceCoreV1NamespacedResourceQuotaStatusOK with default headers values
func NewReplaceCoreV1NamespacedResourceQuotaStatusOK() *ReplaceCoreV1NamespacedResourceQuotaStatusOK {
	return &ReplaceCoreV1NamespacedResourceQuotaStatusOK{}
}

/*ReplaceCoreV1NamespacedResourceQuotaStatusOK handles this case with default header values.

OK
*/
type ReplaceCoreV1NamespacedResourceQuotaStatusOK struct {
	Payload *models.IoK8sAPICoreV1ResourceQuota
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/resourcequotas/{name}/status][%d] replaceCoreV1NamespacedResourceQuotaStatusOK  %+v", 200, o.Payload)
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusOK) GetPayload() *models.IoK8sAPICoreV1ResourceQuota {
	return o.Payload
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPICoreV1ResourceQuota)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCoreV1NamespacedResourceQuotaStatusCreated creates a ReplaceCoreV1NamespacedResourceQuotaStatusCreated with default headers values
func NewReplaceCoreV1NamespacedResourceQuotaStatusCreated() *ReplaceCoreV1NamespacedResourceQuotaStatusCreated {
	return &ReplaceCoreV1NamespacedResourceQuotaStatusCreated{}
}

/*ReplaceCoreV1NamespacedResourceQuotaStatusCreated handles this case with default header values.

Created
*/
type ReplaceCoreV1NamespacedResourceQuotaStatusCreated struct {
	Payload *models.IoK8sAPICoreV1ResourceQuota
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusCreated) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/resourcequotas/{name}/status][%d] replaceCoreV1NamespacedResourceQuotaStatusCreated  %+v", 201, o.Payload)
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusCreated) GetPayload() *models.IoK8sAPICoreV1ResourceQuota {
	return o.Payload
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sAPICoreV1ResourceQuota)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized creates a ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized with default headers values
func NewReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized() *ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized {
	return &ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized{}
}

/*ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized struct {
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v1/namespaces/{namespace}/resourcequotas/{name}/status][%d] replaceCoreV1NamespacedResourceQuotaStatusUnauthorized ", 401)
}

func (o *ReplaceCoreV1NamespacedResourceQuotaStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
