// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package core_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchCoreV1NodeReader is a Reader for the WatchCoreV1Node structure.
type WatchCoreV1NodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WatchCoreV1NodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWatchCoreV1NodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewWatchCoreV1NodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWatchCoreV1NodeOK creates a WatchCoreV1NodeOK with default headers values
func NewWatchCoreV1NodeOK() *WatchCoreV1NodeOK {
	return &WatchCoreV1NodeOK{}
}

/*WatchCoreV1NodeOK handles this case with default header values.

OK
*/
type WatchCoreV1NodeOK struct {
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent
}

func (o *WatchCoreV1NodeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/watch/nodes/{name}][%d] watchCoreV1NodeOK  %+v", 200, o.Payload)
}

func (o *WatchCoreV1NodeOK) GetPayload() *models.IoK8sApimachineryPkgApisMetaV1WatchEvent {
	return o.Payload
}

func (o *WatchCoreV1NodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sApimachineryPkgApisMetaV1WatchEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWatchCoreV1NodeUnauthorized creates a WatchCoreV1NodeUnauthorized with default headers values
func NewWatchCoreV1NodeUnauthorized() *WatchCoreV1NodeUnauthorized {
	return &WatchCoreV1NodeUnauthorized{}
}

/*WatchCoreV1NodeUnauthorized handles this case with default header values.

Unauthorized
*/
type WatchCoreV1NodeUnauthorized struct {
}

func (o *WatchCoreV1NodeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/watch/nodes/{name}][%d] watchCoreV1NodeUnauthorized ", 401)
}

func (o *WatchCoreV1NodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
