// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package admissionregistration_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOKCode is the HTTP code returned for type DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK
const DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOKCode int = 200

/*DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK OK

swagger:response deleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK
*/
type DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status `json:"body,omitempty"`
}

// NewDeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK creates DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK with default headers values
func NewDeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK() *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK {

	return &DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK{}
}

// WithPayload adds the payload to the delete admissionregistration v1 collection mutating webhook configuration o k response
func (o *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete admissionregistration v1 collection mutating webhook configuration o k response
func (o *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorizedCode is the HTTP code returned for type DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized
const DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorizedCode int = 401

/*DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized Unauthorized

swagger:response deleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized
*/
type DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized struct {
}

// NewDeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized creates DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized with default headers values
func NewDeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized() *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized {

	return &DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteAdmissionregistrationV1CollectionMutatingWebhookConfigurationUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
