// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package networking_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// ListNetworkingV1NamespacedIngressOKCode is the HTTP code returned for type ListNetworkingV1NamespacedIngressOK
const ListNetworkingV1NamespacedIngressOKCode int = 200

/*ListNetworkingV1NamespacedIngressOK OK

swagger:response listNetworkingV1NamespacedIngressOK
*/
type ListNetworkingV1NamespacedIngressOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPINetworkingV1IngressList `json:"body,omitempty"`
}

// NewListNetworkingV1NamespacedIngressOK creates ListNetworkingV1NamespacedIngressOK with default headers values
func NewListNetworkingV1NamespacedIngressOK() *ListNetworkingV1NamespacedIngressOK {

	return &ListNetworkingV1NamespacedIngressOK{}
}

// WithPayload adds the payload to the list networking v1 namespaced ingress o k response
func (o *ListNetworkingV1NamespacedIngressOK) WithPayload(payload *models.IoK8sAPINetworkingV1IngressList) *ListNetworkingV1NamespacedIngressOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list networking v1 namespaced ingress o k response
func (o *ListNetworkingV1NamespacedIngressOK) SetPayload(payload *models.IoK8sAPINetworkingV1IngressList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListNetworkingV1NamespacedIngressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListNetworkingV1NamespacedIngressUnauthorizedCode is the HTTP code returned for type ListNetworkingV1NamespacedIngressUnauthorized
const ListNetworkingV1NamespacedIngressUnauthorizedCode int = 401

/*ListNetworkingV1NamespacedIngressUnauthorized Unauthorized

swagger:response listNetworkingV1NamespacedIngressUnauthorized
*/
type ListNetworkingV1NamespacedIngressUnauthorized struct {
}

// NewListNetworkingV1NamespacedIngressUnauthorized creates ListNetworkingV1NamespacedIngressUnauthorized with default headers values
func NewListNetworkingV1NamespacedIngressUnauthorized() *ListNetworkingV1NamespacedIngressUnauthorized {

	return &ListNetworkingV1NamespacedIngressUnauthorized{}
}

// WriteResponse to the client
func (o *ListNetworkingV1NamespacedIngressUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
