// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package events_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// WatchEventsV1EventListForAllNamespacesOKCode is the HTTP code returned for type WatchEventsV1EventListForAllNamespacesOK
const WatchEventsV1EventListForAllNamespacesOKCode int = 200

/*WatchEventsV1EventListForAllNamespacesOK OK

swagger:response watchEventsV1EventListForAllNamespacesOK
*/
type WatchEventsV1EventListForAllNamespacesOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent `json:"body,omitempty"`
}

// NewWatchEventsV1EventListForAllNamespacesOK creates WatchEventsV1EventListForAllNamespacesOK with default headers values
func NewWatchEventsV1EventListForAllNamespacesOK() *WatchEventsV1EventListForAllNamespacesOK {

	return &WatchEventsV1EventListForAllNamespacesOK{}
}

// WithPayload adds the payload to the watch events v1 event list for all namespaces o k response
func (o *WatchEventsV1EventListForAllNamespacesOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) *WatchEventsV1EventListForAllNamespacesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the watch events v1 event list for all namespaces o k response
func (o *WatchEventsV1EventListForAllNamespacesOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1WatchEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WatchEventsV1EventListForAllNamespacesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WatchEventsV1EventListForAllNamespacesUnauthorizedCode is the HTTP code returned for type WatchEventsV1EventListForAllNamespacesUnauthorized
const WatchEventsV1EventListForAllNamespacesUnauthorizedCode int = 401

/*WatchEventsV1EventListForAllNamespacesUnauthorized Unauthorized

swagger:response watchEventsV1EventListForAllNamespacesUnauthorized
*/
type WatchEventsV1EventListForAllNamespacesUnauthorized struct {
}

// NewWatchEventsV1EventListForAllNamespacesUnauthorized creates WatchEventsV1EventListForAllNamespacesUnauthorized with default headers values
func NewWatchEventsV1EventListForAllNamespacesUnauthorized() *WatchEventsV1EventListForAllNamespacesUnauthorized {

	return &WatchEventsV1EventListForAllNamespacesUnauthorized{}
}

// WriteResponse to the client
func (o *WatchEventsV1EventListForAllNamespacesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
