// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package batch_v2alpha1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// DeleteBatchV2alpha1NamespacedCronJobOKCode is the HTTP code returned for type DeleteBatchV2alpha1NamespacedCronJobOK
const DeleteBatchV2alpha1NamespacedCronJobOKCode int = 200

/*DeleteBatchV2alpha1NamespacedCronJobOK OK

swagger:response deleteBatchV2alpha1NamespacedCronJobOK
*/
type DeleteBatchV2alpha1NamespacedCronJobOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status `json:"body,omitempty"`
}

// NewDeleteBatchV2alpha1NamespacedCronJobOK creates DeleteBatchV2alpha1NamespacedCronJobOK with default headers values
func NewDeleteBatchV2alpha1NamespacedCronJobOK() *DeleteBatchV2alpha1NamespacedCronJobOK {

	return &DeleteBatchV2alpha1NamespacedCronJobOK{}
}

// WithPayload adds the payload to the delete batch v2alpha1 namespaced cron job o k response
func (o *DeleteBatchV2alpha1NamespacedCronJobOK) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) *DeleteBatchV2alpha1NamespacedCronJobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete batch v2alpha1 namespaced cron job o k response
func (o *DeleteBatchV2alpha1NamespacedCronJobOK) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBatchV2alpha1NamespacedCronJobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBatchV2alpha1NamespacedCronJobAcceptedCode is the HTTP code returned for type DeleteBatchV2alpha1NamespacedCronJobAccepted
const DeleteBatchV2alpha1NamespacedCronJobAcceptedCode int = 202

/*DeleteBatchV2alpha1NamespacedCronJobAccepted Accepted

swagger:response deleteBatchV2alpha1NamespacedCronJobAccepted
*/
type DeleteBatchV2alpha1NamespacedCronJobAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sApimachineryPkgApisMetaV1Status `json:"body,omitempty"`
}

// NewDeleteBatchV2alpha1NamespacedCronJobAccepted creates DeleteBatchV2alpha1NamespacedCronJobAccepted with default headers values
func NewDeleteBatchV2alpha1NamespacedCronJobAccepted() *DeleteBatchV2alpha1NamespacedCronJobAccepted {

	return &DeleteBatchV2alpha1NamespacedCronJobAccepted{}
}

// WithPayload adds the payload to the delete batch v2alpha1 namespaced cron job accepted response
func (o *DeleteBatchV2alpha1NamespacedCronJobAccepted) WithPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) *DeleteBatchV2alpha1NamespacedCronJobAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete batch v2alpha1 namespaced cron job accepted response
func (o *DeleteBatchV2alpha1NamespacedCronJobAccepted) SetPayload(payload *models.IoK8sApimachineryPkgApisMetaV1Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBatchV2alpha1NamespacedCronJobAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBatchV2alpha1NamespacedCronJobUnauthorizedCode is the HTTP code returned for type DeleteBatchV2alpha1NamespacedCronJobUnauthorized
const DeleteBatchV2alpha1NamespacedCronJobUnauthorizedCode int = 401

/*DeleteBatchV2alpha1NamespacedCronJobUnauthorized Unauthorized

swagger:response deleteBatchV2alpha1NamespacedCronJobUnauthorized
*/
type DeleteBatchV2alpha1NamespacedCronJobUnauthorized struct {
}

// NewDeleteBatchV2alpha1NamespacedCronJobUnauthorized creates DeleteBatchV2alpha1NamespacedCronJobUnauthorized with default headers values
func NewDeleteBatchV2alpha1NamespacedCronJobUnauthorized() *DeleteBatchV2alpha1NamespacedCronJobUnauthorized {

	return &DeleteBatchV2alpha1NamespacedCronJobUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteBatchV2alpha1NamespacedCronJobUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
