// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package autoscaling_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/kube-apate/api/k8s/v1/models"
)

// PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOKCode is the HTTP code returned for type PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK
const PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOKCode int = 200

/*PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK OK

swagger:response patchAutoscalingV1NamespacedHorizontalPodAutoscalerOK
*/
type PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK struct {

	/*
	  In: Body
	*/
	Payload *models.IoK8sAPIAutoscalingV1HorizontalPodAutoscaler `json:"body,omitempty"`
}

// NewPatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK creates PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK with default headers values
func NewPatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK() *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK {

	return &PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK{}
}

// WithPayload adds the payload to the patch autoscaling v1 namespaced horizontal pod autoscaler o k response
func (o *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK) WithPayload(payload *models.IoK8sAPIAutoscalingV1HorizontalPodAutoscaler) *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch autoscaling v1 namespaced horizontal pod autoscaler o k response
func (o *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK) SetPayload(payload *models.IoK8sAPIAutoscalingV1HorizontalPodAutoscaler) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorizedCode is the HTTP code returned for type PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized
const PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorizedCode int = 401

/*PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized Unauthorized

swagger:response patchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized
*/
type PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized struct {
}

// NewPatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized creates PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized with default headers values
func NewPatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized() *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized {

	return &PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized{}
}

// WriteResponse to the client
func (o *PatchAutoscalingV1NamespacedHorizontalPodAutoscalerUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
